// `docs` — the project's GENERATED documents and whether they are stale
// (2026-10-01). Zero tokens; the generator is shown, never run.
import { resolve } from "node:path";
import { parseArgs } from "node:util";
import { docsStatus, loadDocs, saveDocs, validateDoc } from "../../src/server/docs_registry.ts";
import { cliPath } from "./winpath.mjs";

export const DOCS_USAGE = `docs list | check | add <path> --generator "<cmd>" --inputs <a,b/,c/**> | remove <path>   [--root <dir>] [--json]
                                  generated documents (.vibegraph/docs.json): each one's generator and the inputs it
                                  is derived from; \`check\` says which are stale since which commit (git), exit 1 if any`;

const list = (v) => (v ?? "").split(",").map((s) => s.trim()).filter(Boolean);

export function runDocs(args) {
  let parsed;
  try {
    parsed = parseArgs({ args, allowPositionals: true, options: { root: { type: "string" }, json: { type: "boolean" }, generator: { type: "string" }, inputs: { type: "string" }, note: { type: "string" } } });
  } catch (e) { return { exitCode: 2, text: `${e.message}\n\nusage: vibegraph-knowledge ${DOCS_USAGE}\n` }; }
  const [sub, target] = parsed.positionals;
  const root = resolve(cliPath(parsed.values.root ?? "."));
  const done = (text, exitCode = 0) => ({ exitCode, text: text.endsWith("\n") ? text : `${text}\n` });
  if (sub === "add") {
    const doc = { path: target, generator: parsed.values.generator, inputs: list(parsed.values.inputs), ...(parsed.values.note ? { note: parsed.values.note } : {}) };
    const bad = validateDoc(doc);
    if (bad) return done(`refused: ${bad}`, 2);
    const docs = loadDocs(root).filter((d) => d.path !== doc.path);
    saveDocs(root, [...docs, doc]);
    return done(`registered ${doc.path} (generated by \`${doc.generator}\` from ${doc.inputs.join(", ")})`);
  }
  if (sub === "remove") {
    const docs = loadDocs(root);
    if (!docs.some((d) => d.path === target)) return done(`no registered doc ${target ?? ""}`, 1);
    saveDocs(root, docs.filter((d) => d.path !== target));
    return done(`removed ${target} from the registry (the file itself is untouched)`);
  }
  if (sub === "list" || sub === "check") {
    const rows = docsStatus(root);
    if (parsed.values.json) return done(JSON.stringify(rows, null, 2), sub === "check" && rows.some((r) => r.state === "stale") ? 1 : 0);
    if (!rows.length) return done("no generated documents registered — `vibegraph-knowledge docs add <path> --generator \"<cmd>\" --inputs <paths>`");
    const text = rows.map((r) => `${r.state === "stale" ? "STALE" : r.state === "unknown" ? "?    " : "fresh"}  ${r.doc.path} — ${r.detail}`).join("\n");
    return done(text, sub === "check" && rows.some((r) => r.state === "stale") ? 1 : 0);
  }
  return done(`usage: vibegraph-knowledge ${DOCS_USAGE}`, 2);
}
