// M-CRYSTAL.4 — `init`: the pointer. Plain `claude -p` reads the cwd's
// CLAUDE.md on its own, and h2h3 arm D added exactly one thing to what the
// constraints-on-disk arm had: a CLAUDE.md that said where the folder was
// and to read it first. That arm opened the index, the constraints, the
// plan and three contracts, and kept every rule. This writes that pointer.
//
// It touches two files the person owns, so both writes are marked and
// idempotent: the CLAUDE.md block sits between markers and is REPLACED on
// a re-run, never duplicated; the .gitignore line is added once. `--print`
// shows the block and writes nothing. No hook is installed (D7).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const BEGIN = "<!-- vibegraph-knowledge:begin -->";
export const END = "<!-- vibegraph-knowledge:end -->";
export const IGNORE_LINE = ".vibegraph/knowledge/";

export const POINTER = [
  BEGIN,
  "# Read this first",
  "",
  "VibeGraph analysed this codebase and wrote what it derived to",
  "`.vibegraph/knowledge/` (index: `.vibegraph/knowledge/README.md`). Read",
  "that index before changing anything. It holds the operators' stated",
  "rules (`constraints.md` — rules the code does not reveal), one contract",
  "per code thread (`threads/`), the ratified per-thread skills (`skills/`,",
  "when any exist) and, when a task was given, a dependency-ordered plan",
  "(`plan.md`). Treat the stated rules as requirements from the people who",
  "run this service. Do not edit anything under `.vibegraph/`.",
  "",
  "The folder is regenerated by `npx vibegraph-knowledge export` (seconds,",
  "no model) and goes stale as you edit: re-run it rather than trusting an",
  "old copy. `npx vibegraph-knowledge check --uncommitted` verifies every",
  "stated rule's checkable half against the code as it is now, with your",
  "uncommitted changes as the delta — run it before you finish;",
  "exit 1 names the offending node, exit 2 means a rule could not be",
  "verified, which is not a pass.",
  END,
].join("\n");

function upsertBlock(existing) {
  const b = existing.indexOf(BEGIN);
  const e = existing.indexOf(END);
  if (b >= 0 && e > b) return existing.slice(0, b) + POINTER + existing.slice(e + END.length);
  const sep = existing.length === 0 ? "" : existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
  return `${existing}${sep}${POINTER}\n`;
}

function hasIgnore(text) {
  return text.split("\n").some((l) => {
    const t = l.trim();
    return t === IGNORE_LINE || t === `/${IGNORE_LINE}` || t === `**/${IGNORE_LINE}` || t === IGNORE_LINE.slice(0, -1) || t === ".vibegraph/";
  });
}

/**
 * @returns {{ claudeMd: "created"|"updated"|"unchanged"|"printed", gitignore: "created"|"updated"|"unchanged"|"skipped", paths: {claudeMd, gitignore} }}
 */
export function applyInit({ root, print = false }) {
  const claudeMd = join(root, "CLAUDE.md");
  const gitignore = join(root, ".gitignore");
  if (print) return { claudeMd: "printed", gitignore: "skipped", paths: { claudeMd, gitignore } };

  let claudeState;
  if (!existsSync(claudeMd)) {
    writeFileSync(claudeMd, POINTER + "\n");
    claudeState = "created";
  } else {
    const before = readFileSync(claudeMd, "utf-8");
    const after = upsertBlock(before);
    if (after === before) claudeState = "unchanged";
    else { writeFileSync(claudeMd, after); claudeState = "updated"; }
  }

  let ignoreState;
  const entry = `# vibegraph-knowledge: generated in seconds, stale on the first edit — never commit it\n${IGNORE_LINE}\n`;
  if (!existsSync(gitignore)) {
    writeFileSync(gitignore, entry);
    ignoreState = "created";
  } else {
    const before = readFileSync(gitignore, "utf-8");
    if (hasIgnore(before)) ignoreState = "unchanged";
    else {
      writeFileSync(gitignore, `${before}${before.length === 0 || before.endsWith("\n") ? "" : "\n"}${entry}`);
      ignoreState = "updated";
    }
  }
  return { claudeMd: claudeState, gitignore: ignoreState, paths: { claudeMd, gitignore } };
}
