// M-CRYSTAL.4 — `init`: the pointer. Plain `claude -p` reads the cwd's
// CLAUDE.md on its own, and h2h3 arm D added exactly one thing to what the
// constraints-on-disk arm had: a CLAUDE.md that said where the folder was
// and to read it first. That arm opened the index, the constraints, the
// plan and three contracts, and kept every rule. This writes that pointer.
//
// It touches two files the person owns, so both writes are marked and
// idempotent: the CLAUDE.md block sits between markers and is REPLACED on
// a re-run, never duplicated; the .gitignore line is added once. `--print`
// shows the block and writes nothing. No hook is installed unless asked
// (`--hooks`, below).
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { PACKAGE_NAME } from "./paths.mjs";

export const BEGIN = "<!-- vibegraph-knowledge:begin -->";
export const END = "<!-- vibegraph-knowledge:end -->";
export const IGNORE_LINE = ".vibegraph/knowledge/";

export const POINTER = [
  BEGIN,
  "# Read this first",
  "",
  "VibeGraph analysed this codebase and wrote what it derived to",
  "`.vibegraph/knowledge/` (index: `.vibegraph/knowledge/README.md`). Read",
  "that index before changing anything. It holds the operators' stated",
  "rules (`constraints.md` — rules the code does not reveal), one contract",
  "per code thread (`threads/`), the ratified per-thread skills (`skills/`,",
  "when any exist) and, when a task was given, a dependency-ordered plan",
  "(`plan.md`). Treat the stated rules as requirements from the people who",
  "run this service. Do not edit anything under `.vibegraph/`.",
  "",
  "The folder is regenerated by `npx vibegraph-knowledge export` (seconds,",
  "no model) and goes stale as you edit: re-run it rather than trusting an",
  "old copy. `npx vibegraph-knowledge check --uncommitted` verifies every",
  "stated rule's checkable half against the code as it is now, with your",
  "uncommitted changes as the delta — run it before you finish;",
  "exit 1 names the offending node, exit 2 means a rule could not be",
  "verified, which is not a pass.",
  "",
  "Never claim code is unused, dead, untested or unconfigured because the",
  "folder does not mention it. Check first: `reachability.md` says why a",
  "function is on no thread (some reasons mean it IS used), and",
  "`npx vibegraph-knowledge coverage <file>…` says whether a file was fully",
  "parsed, what reaches and tests it, what environment it reads, and",
  "whether it changed since the export. `npx vibegraph-knowledge affected",
  "--uncommitted` lists the tests to run for your changes.",
  "",
  "A stated rule that looks wrong or too tight is not yours to change:",
  "`npx vibegraph-knowledge constraint propose <id> --check '<clause>' --why",
  "\"<reason>\"` records the change for a person to accept. If VibeGraph hooks",
  "are installed but their context never arrives, `npx vibegraph-knowledge",
  "doctor` says why; `hook run <event> --file <path>` fires one by hand.",
  END,
].join("\n");

function upsertBlock(existing) {
  const b = existing.indexOf(BEGIN);
  const e = existing.indexOf(END);
  if (b >= 0 && e > b) return existing.slice(0, b) + POINTER + existing.slice(e + END.length);
  const sep = existing.length === 0 ? "" : existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
  return `${existing}${sep}${POINTER}\n`;
}

function hasIgnore(text) {
  return text.split("\n").some((l) => {
    const t = l.trim();
    return t === IGNORE_LINE || t === `/${IGNORE_LINE}` || t === `**/${IGNORE_LINE}` || t === IGNORE_LINE.slice(0, -1) || t === ".vibegraph/";
  });
}

/**
 * @returns {{ claudeMd: "created"|"updated"|"unchanged"|"printed", gitignore: "created"|"updated"|"unchanged"|"skipped", paths: {claudeMd, gitignore} }}
 */
export function applyInit({ root, print = false }) {
  const claudeMd = join(root, "CLAUDE.md");
  const gitignore = join(root, ".gitignore");
  if (print) return { claudeMd: "printed", gitignore: "skipped", paths: { claudeMd, gitignore } };

  let claudeState;
  if (!existsSync(claudeMd)) {
    writeFileSync(claudeMd, POINTER + "\n");
    claudeState = "created";
  } else {
    const before = readFileSync(claudeMd, "utf-8");
    const after = upsertBlock(before);
    if (after === before) claudeState = "unchanged";
    else { writeFileSync(claudeMd, after); claudeState = "updated"; }
  }

  let ignoreState;
  const entry = `# vibegraph-knowledge: generated in seconds, stale on the first edit — never commit it\n${IGNORE_LINE}\n`;
  if (!existsSync(gitignore)) {
    writeFileSync(gitignore, entry);
    ignoreState = "created";
  } else {
    const before = readFileSync(gitignore, "utf-8");
    if (hasIgnore(before)) ignoreState = "unchanged";
    else {
      writeFileSync(gitignore, `${before}${before.length === 0 || before.endsWith("\n") ? "" : "\n"}${entry}`);
      ignoreState = "updated";
    }
  }
  return { claudeMd: claudeState, gitignore: ignoreState, paths: { claudeMd, gitignore } };
}

// ── `init --hooks` (2026-09-28) ─────────────────────────────────────────
// Opt-in only, and the reversal of D7 is Ben's call ("go with your proposed
// plan" after the hooks were explained): four Claude Code hooks that run
// `vibegraph-knowledge hook <event>` (scripts/cli/hooks.mjs). Written to
// .claude/settings.local.json — the PER-USER settings file, never committed —
// because the command names this machine's node and CLI by absolute path.
// Entries are recognised by the trailing `--vg-hook` marker, so a re-run
// replaces them and `--remove-hooks` takes exactly them out; every other hook
// in the file is left alone.

export const HOOK_MARKER = "--vg-hook";
const HOOK_SPECS = [
  // Every source: startup orients; compact / clear reset what "already
  // delivered" means, since that context is gone (2026-09-29).
  { claudeEvent: "SessionStart", event: "session-start", timeout: 60 },
  { claudeEvent: "UserPromptSubmit", event: "prompt", timeout: 60 },
  { claudeEvent: "PostToolUse", event: "post-edit", timeout: 120, matcher: "Write|Edit|MultiEdit|NotebookEdit|Bash|PowerShell" },
  { claudeEvent: "Stop", event: "stop", timeout: 180 },
];

const q = (s) => `"${String(s).replace(/(["\\$`])/g, "\\$1")}"`;

/** The command a hook runs: this node, its flags, this CLI — as run now —
 *  with the Python it verified PINNED in front (`env`: VG_PYTHON and, when
 *  libcst came from a directory, VIBEGRAPH_PYDEPS). Claude Code runs hooks
 *  with whatever PATH it was started under; an unpinned hook once found the
 *  system Python 3.12, which could not load a libcst built for 3.13, and
 *  parsed no Python at all. */
export function hookCommand(root, event, env = {}, argv = process.argv, execPath = process.execPath, execArgv = process.execArgv, version = null) {
  const prefix = Object.entries(env).map(([k, v]) => `${k}=${q(v)}`);
  return [...prefix, ...cliInvocation(argv, execPath, execArgv, version), "hook", event, "--root", q(root), HOOK_MARKER].join(" ");
}

/** 2026-10-01 — `init --hooks --windows`: the same hook for a Claude Code
 *  running on WINDOWS against a project inside WSL (opened as
 *  \\wsl.localhost\<distro>\…). A Linux path means nothing to Windows, so the
 *  hook is ONE executable with arguments — `wsl.exe -d <distro> -e env
 *  VG_PYTHON=… node cli hook <event> --root /linux/root` — which Git Bash,
 *  PowerShell and cmd all run alike (no shell syntax: no `VAR=x` prefix, no
 *  `$`), and which a session inside WSL can still run through interop.
 *  stdin, stdout, stderr and the exit code (2 = block) pass through wsl.exe.
 *  Every token is single-quoted when it needs quoting, which both shells read
 *  literally; a path holding a single quote is refused rather than escaped
 *  two different ways. An npx run cannot be pinned (its cache path moves and
 *  `wsl.exe -e` has no login PATH to find npx on), so it is refused too. */
export function windowsHookCommand(root, event, env = {}, distro = process.env.WSL_DISTRO_NAME, argv = process.argv, execPath = process.execPath, execArgv = process.execArgv) {
  if (!distro) throw new Error("--windows writes hooks that call into WSL: run init from inside the WSL distro that holds the project");
  const script = String(argv[1] ?? "");
  if (/[\\/]_npx[\\/]/.test(script)) throw new Error("--windows needs an installed CLI (npm install -g vibegraph-knowledge) — an npx cache path is not stable");
  const sq = (s) => {
    s = String(s);
    if (/^[\w./@:=+,-]+$/.test(s)) return s;
    if (s.includes("'")) throw new Error(`--windows cannot quote a path holding a single quote: ${s}`);
    return `'${s}'`;
  };
  // Git Bash — Claude Code's default hook shell on Windows — rewrites any
  // argument that looks like a POSIX path before handing it to a Windows
  // program (`/tmp/x` arrived in WSL as `C:/Users/…/Temp/x`, `/usr/bin/env` as
  // `C:/Program Files/Git/usr/bin/env`). A DOUBLE leading slash passes Git Bash
  // and PowerShell untouched (measured both), and Linux reads `//x` as `/x`;
  // the hook folds it back (`fromWindowsPath`'s neighbour in main.mjs).
  const posix = (s) => (String(s).startsWith("/") && !String(s).startsWith("//") ? `/${s}` : String(s));
  const envArgs = Object.entries(env).map(([k, v]) => `${k}=${posix(v)}`);
  return ["wsl.exe", "-d", distro, "-e", posix("/usr/bin/env"), ...envArgs, posix(execPath), ...execArgv, posix(script), "hook", event, "--root", posix(root), HOOK_MARKER].map(sq).join(" ");
}

/** How a hook reaches this CLI again. Run from npx, the script lives in
 *  npx's cache (`…/_npx/<hash>/…`), which npm may clean at any time — a hook
 *  pinned to it would stop working without a word. So an npx run writes
 *  `npx --yes vibegraph-knowledge@<this version>` (slower to start, stable);
 *  a global or project install writes its own path. */
export function cliInvocation(argv = process.argv, execPath = process.execPath, execArgv = process.execArgv, version = null) {
  const script = String(argv[1] ?? "");
  if (/[\\/]_npx[\\/]/.test(script)) return ["npx", "--yes", `${PACKAGE_NAME}@${version ?? "latest"}`];
  return [q(execPath), ...execArgv.map(q), q(script)];
}

// ── `init --skill` (2026-09-28) ─────────────────────────────────────────
// The Claude Code skill this package ships (scripts/cli/claude-skill/SKILL.md,
// vendored to vendor/claude-skill/): what lets a plain Claude chat set
// VibeGraph up and use it without anyone reading the docs. Into the
// project's .claude/skills/, or with `user` into ~/.claude/skills/ so every
// project on the machine has it.

export const SKILL_NAME = "vibegraph";

// 2026-09-29 — the TASK skills: when to open which crystallised file for
// planning, debugging, a security review and a pre-commit review. Claude Code
// keeps only a skill's name and description in context until a task matches,
// so these cost ~100 tokens each until used. scripts/cli/claude-skills/<name>/.
export const TASK_SKILLS = ["plan", "debug", "security", "review"];
export const ALL_SKILLS = [SKILL_NAME, ...TASK_SKILLS.map((t) => `${SKILL_NAME}-${t}`)];

/** `plan,debug` → ["vibegraph", "vibegraph-plan", "vibegraph-debug"]; the
 *  setup skill always comes along. Unknown names are refused, never guessed. */
export function skillsFromList(list) {
  if (!list) return ALL_SKILLS;
  const wanted = list.split(",").map((s) => s.trim().replace(/^vibegraph-?/, "")).filter(Boolean);
  const bad = wanted.filter((w) => !TASK_SKILLS.includes(w));
  if (bad.length) throw new Error(`unknown skill(s): ${bad.join(", ")} — one of: ${TASK_SKILLS.join(", ")}`);
  return [SKILL_NAME, ...wanted.map((w) => `${SKILL_NAME}-${w}`)];
}

export function skillSource(loc, name = SKILL_NAME) {
  if (name !== SKILL_NAME) {
    return loc.mode === "installed"
      ? join(loc.packageRoot, "vendor", "claude-skills", name, "SKILL.md")
      : join(loc.repoRoot, "scripts", "cli", "claude-skills", name, "SKILL.md");
  }
  return loc.mode === "installed"
    ? join(loc.packageRoot, "vendor", "claude-skill", "SKILL.md")
    : join(loc.repoRoot, "scripts", "cli", "claude-skill", "SKILL.md");
}

/** @returns {{ path, state: "installed"|"updated"|"unchanged"|"removed"|"absent" }} */
/** Install (or remove) several skills; one result per skill. */
export function applySkills({ names = ALL_SKILLS, ...rest }) {
  return names.map((name) => ({ name, ...applySkill({ ...rest, name }) }));
}

export function applySkill({ root, loc, user = false, remove = false, home = homedir(), name = SKILL_NAME }) {
  const dir = join(user ? join(home, ".claude") : join(root, ".claude"), "skills", name);
  const path = join(dir, "SKILL.md");
  if (remove) {
    if (!existsSync(path)) return { path, state: "absent" };
    rmSync(dir, { recursive: true, force: true });
    return { path, state: "removed" };
  }
  const body = readFileSync(skillSource(loc, name), "utf-8");
  const had = existsSync(path) ? readFileSync(path, "utf-8") : null;
  if (had === body) return { path, state: "unchanged" };
  mkdirSync(dir, { recursive: true });
  writeFileSync(path, body);
  return { path, state: had === null ? "installed" : "updated" };
}

const isOurs = (h) => typeof h?.command === "string" && h.command.includes(HOOK_MARKER);

/** @returns {{ path, state: "installed"|"updated"|"removed"|"unchanged" }} */
export function applyHooks({ root, remove = false, command = hookCommand }) {
  const dir = join(root, ".claude");
  const path = join(dir, "settings.local.json");
  let settings = {};
  if (existsSync(path)) {
    try { settings = JSON.parse(readFileSync(path, "utf-8")); }
    catch (e) { throw new Error(`${path} is not valid JSON (${e.message}); fix it or move it aside — it was not changed`); }
  }
  const before = JSON.stringify(settings);
  const hooks = { ...(settings.hooks ?? {}) };
  for (const spec of HOOK_SPECS) {
    const groups = (hooks[spec.claudeEvent] ?? [])
      .map((g) => ({ ...g, hooks: (g.hooks ?? []).filter((h) => !isOurs(h)) }))
      .filter((g) => g.hooks.length > 0);
    if (!remove) {
      groups.push({
        ...(spec.matcher ? { matcher: spec.matcher } : {}),
        hooks: [{ type: "command", command: command(root, spec.event), timeout: spec.timeout }],
      });
    }
    if (groups.length) hooks[spec.claudeEvent] = groups; else delete hooks[spec.claudeEvent];
  }
  const next = { ...settings };
  if (Object.keys(hooks).length) next.hooks = hooks; else delete next.hooks;
  const had = before.includes(HOOK_MARKER);
  if (JSON.stringify(next) === before) return { path, state: "unchanged" };
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(path, JSON.stringify(next, null, 2) + "\n");
  return { path, state: remove ? "removed" : had ? "updated" : "installed" };
}
