// GENERATED by scripts/gen_stack_tables.mjs — DO NOT EDIT BY HAND.
//
// The standard library of each language, asked of the language itself
// rather than remembered. Regenerate with:
//
//   node scripts/gen_stack_tables.mjs
//
// `npm run test:stack-tables` fails if this file has drifted from what
// the runtimes report, so the tables cannot quietly rot the way the
// hand-written ones did (87 of Python's 192 stdlib roots, which made
// `origin: "third-party"` a false claim about 105 standard modules).
//
// A version stamp is not decoration: `sys.stdlib_module_names` describes
// ONE interpreter version. PYTHON_STDLIB_REMOVED carries the modules that
// used to be standard so an older project is not accused of a dependency.

export const GENERATED_FROM = {
  python: "3.13.13",
  node: "24.15.0",
  bash: "5.2.21(1)-release",
} as const;

/** `sys.stdlib_module_names` — every module this Python ships, complete. */
export const PYTHON_STDLIB_CURRENT: readonly string[] = [
  "abc", "antigravity", "argparse", "array", "ast", "asyncio", "atexit",
  "base64", "bdb", "binascii", "bisect", "builtins", "bz2", "cProfile",
  "calendar", "cmath", "cmd", "code", "codecs", "codeop", "collections",
  "colorsys", "compileall", "concurrent", "configparser", "contextlib",
  "contextvars", "copy", "copyreg", "csv", "ctypes", "curses", "dataclasses",
  "datetime", "dbm", "decimal", "difflib", "dis", "doctest", "email",
  "encodings", "ensurepip", "enum", "errno", "faulthandler", "fcntl",
  "filecmp", "fileinput", "fnmatch", "fractions", "ftplib", "functools", "gc",
  "genericpath", "getopt", "getpass", "gettext", "glob", "graphlib", "grp",
  "gzip", "hashlib", "heapq", "hmac", "html", "http", "idlelib", "imaplib",
  "importlib", "inspect", "io", "ipaddress", "itertools", "json", "keyword",
  "linecache", "locale", "logging", "lzma", "mailbox", "marshal", "math",
  "mimetypes", "mmap", "modulefinder", "msvcrt", "multiprocessing", "netrc",
  "nt", "ntpath", "nturl2path", "numbers", "opcode", "operator", "optparse",
  "os", "pathlib", "pdb", "pickle", "pickletools", "pkgutil", "platform",
  "plistlib", "poplib", "posix", "posixpath", "pprint", "profile", "pstats",
  "pty", "pwd", "py_compile", "pyclbr", "pydoc", "pydoc_data", "pyexpat",
  "queue", "quopri", "random", "re", "readline", "reprlib", "resource",
  "rlcompleter", "runpy", "sched", "secrets", "select", "selectors", "shelve",
  "shlex", "shutil", "signal", "site", "smtplib", "socket", "socketserver",
  "sqlite3", "sre_compile", "sre_constants", "sre_parse", "ssl", "stat",
  "statistics", "string", "stringprep", "struct", "subprocess", "symtable",
  "sys", "sysconfig", "syslog", "tabnanny", "tarfile", "tempfile", "termios",
  "textwrap", "this", "threading", "time", "timeit", "tkinter", "token",
  "tokenize", "tomllib", "trace", "traceback", "tracemalloc", "tty", "turtle",
  "turtledemo", "types", "typing", "unicodedata", "unittest", "urllib",
  "uuid", "venv", "warnings", "wave", "weakref", "webbrowser", "winreg",
  "winsound", "wsgiref", "xml", "xmlrpc", "zipapp", "zipfile", "zipimport",
  "zlib", "zoneinfo",
];

/** Modules removed from the standard library (PEP 594 + the 3.12 cuts). A
 *  project on an older interpreter imports these legitimately. */
export const PYTHON_STDLIB_REMOVED: readonly string[] = [
  "aifc", "asynchat", "asyncore", "audioop", "binhex", "cgi", "cgitb",
  "chunk", "crypt", "distutils", "formatter", "imghdr", "imp", "lib2to3",
  "macpath", "mailcap", "msilib", "nis", "nntplib", "ossaudiodev", "parser",
  "pipes", "smtpd", "sndhdr", "spwd", "sunau", "symbol", "telnetlib", "uu",
  "xdrlib",
];

/** `dir(builtins)`, callables only — every name Python resolves without an
 *  import, INCLUDING every exception constructor (a `raise ValueError(...)`
 *  is a call node, and before M-RESOLVE one inside a funnel briefly read as
 *  a subprocess round trip). */
export const PYTHON_BUILTIN_NAMES: readonly string[] = [
  "ArithmeticError", "AssertionError", "AttributeError", "BaseException",
  "BaseExceptionGroup", "BlockingIOError", "BrokenPipeError", "BufferError",
  "BytesWarning", "ChildProcessError", "ConnectionAbortedError",
  "ConnectionError", "ConnectionRefusedError", "ConnectionResetError",
  "DeprecationWarning", "EOFError", "EncodingWarning", "EnvironmentError",
  "Exception", "ExceptionGroup", "FileExistsError", "FileNotFoundError",
  "FloatingPointError", "FutureWarning", "GeneratorExit", "IOError",
  "ImportError", "ImportWarning", "IndentationError", "IndexError",
  "InterruptedError", "IsADirectoryError", "KeyError", "KeyboardInterrupt",
  "LookupError", "MemoryError", "ModuleNotFoundError", "NameError",
  "NotADirectoryError", "NotImplementedError", "OSError", "OverflowError",
  "PendingDeprecationWarning", "PermissionError", "ProcessLookupError",
  "PythonFinalizationError", "RecursionError", "ReferenceError",
  "ResourceWarning", "RuntimeError", "RuntimeWarning", "StopAsyncIteration",
  "StopIteration", "SyntaxError", "SyntaxWarning", "SystemError",
  "SystemExit", "TabError", "TimeoutError", "TypeError", "UnboundLocalError",
  "UnicodeDecodeError", "UnicodeEncodeError", "UnicodeError",
  "UnicodeTranslateError", "UnicodeWarning", "UserWarning", "ValueError",
  "Warning", "ZeroDivisionError", "abs", "aiter", "all", "anext", "any",
  "ascii", "bin", "bool", "breakpoint", "bytearray", "bytes", "callable",
  "chr", "classmethod", "compile", "complex", "copyright", "credits",
  "delattr", "dict", "dir", "divmod", "enumerate", "eval", "exec", "exit",
  "filter", "float", "format", "frozenset", "getattr", "globals", "hasattr",
  "hash", "help", "hex", "id", "input", "int", "isinstance", "issubclass",
  "iter", "len", "license", "list", "locals", "map", "max", "memoryview",
  "min", "next", "object", "oct", "open", "ord", "pow", "print", "property",
  "quit", "range", "repr", "reversed", "round", "set", "setattr", "slice",
  "sorted", "staticmethod", "str", "sum", "super", "tuple", "type", "vars",
  "zip",
];

/** `module.builtinModules`, `node:` prefix stripped. */
export const NODE_BUILTIN_NAMES: readonly string[] = [
  "assert", "async_hooks", "buffer", "child_process", "cluster", "console",
  "constants", "crypto", "dgram", "diagnostics_channel", "dns", "domain",
  "events", "fs", "http", "http2", "https", "inspector", "module", "net",
  "os", "path", "perf_hooks", "process", "punycode", "querystring",
  "readline", "repl", "sea", "sqlite", "stream", "string_decoder", "sys",
  "test", "timers", "tls", "trace_events", "tty", "url", "util", "v8", "vm",
  "wasi", "worker_threads", "zlib",
];

/** `compgen -b` — the shell's OWN builtins, and nothing else. What bash
 *  scripts mostly call is external binaries, and no list can enumerate
 *  those: `command -v` would answer for the analysing machine, not the
 *  host the script deploys to. Coreutils plumbing is a separate, curated
 *  list in stack_taxonomy.ts; anything in neither is `origin: "unknown"`. */
export const BASH_SHELL_BUILTIN_NAMES: readonly string[] = [
  ".", ":", "[", "alias", "bg", "bind", "break", "builtin", "caller", "cd",
  "command", "compgen", "complete", "compopt", "continue", "declare", "dirs",
  "disown", "echo", "enable", "eval", "exec", "exit", "export", "false", "fc",
  "fg", "getopts", "hash", "help", "history", "jobs", "kill", "let", "local",
  "logout", "mapfile", "popd", "printf", "pushd", "pwd", "read", "readarray",
  "readonly", "return", "set", "shift", "shopt", "source", "suspend", "test",
  "times", "trap", "true", "type", "typeset", "ulimit", "umask", "unalias",
  "unset", "wait",
];

/** `compgen -k` — the shell's reserved words. Parsed, never executed, so
 *  never a tool and never a dependency. */
export const BASH_KEYWORD_NAMES: readonly string[] = [
  "!", "[[", "]]", "case", "coproc", "do", "done", "elif", "else", "esac",
  "fi", "for", "function", "if", "in", "select", "then", "time", "until",
  "while", "{", "}",
];
