// module 11: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step11_0(n: number): number {
  console.log("module 11 step 0", n);
  return step11_1(n + 1);
}
export function step11_1(n: number): number {
  console.log("module 11 step 1", n);
  return step11_2(n + 1);
}
export function step11_2(n: number): number {
  console.log("module 11 step 2", n);
  return step11_3(n + 1);
}
export function step11_3(n: number): number {
  console.log("module 11 step 3", n);
  return step11_4(n + 1);
}
export function step11_4(n: number): number {
  console.log("module 11 step 4", n);
  return step11_5(n + 1);
}
export function step11_5(n: number): number {
  console.log("module 11 step 5", n);
  return step11_6(n + 1);
}
export function step11_6(n: number): number {
  console.log("module 11 step 6", n);
  return step11_7(n + 1);
}
export function step11_7(n: number): number {
  console.log("module 11 step 7", n);
  return step11_8(n + 1);
}
export function step11_8(n: number): number {
  console.log("module 11 step 8", n);
  return step11_9(n + 1);
}
export function step11_9(n: number): number {
  console.log("module 11 step 9", n);
  return step11_10(n + 1);
}
export function step11_10(n: number): number {
  console.log("module 11 step 10", n);
  return step11_11(n + 1);
}
export function step11_11(n: number): number {
  console.log("module 11 step 11", n);
  return step11_12(n + 1);
}
export function step11_12(n: number): number {
  console.log("module 11 step 12", n);
  return step11_13(n + 1);
}
export function step11_13(n: number): number {
  console.log("module 11 step 13", n);
  return step11_14(n + 1);
}
export function step11_14(n: number): number {
  console.log("module 11 step 14", n);
  return step11_15(n + 1);
}
export function step11_15(n: number): number {
  console.log("module 11 step 15", n);
  return step11_16(n + 1);
}
export function step11_16(n: number): number {
  console.log("module 11 step 16", n);
  return step11_17(n + 1);
}
export function step11_17(n: number): number {
  console.log("module 11 step 17", n);
  return step11_18(n + 1);
}
export function step11_18(n: number): number {
  console.log("module 11 step 18", n);
  return step11_19(n + 1);
}
export function step11_19(n: number): number {
  console.log("module 11 step 19", n);
  return step11_20(n + 1);
}
export function step11_20(n: number): number {
  console.log("module 11 step 20", n);
  return step11_21(n + 1);
}
export function step11_21(n: number): number {
  console.log("module 11 step 21", n);
  return step11_22(n + 1);
}
export function step11_22(n: number): number {
  console.log("module 11 step 22", n);
  return step11_23(n + 1);
}
export function step11_23(n: number): number {
  console.log("module 11 step 23", n);
  return step11_24(n + 1);
}
export function step11_24(n: number): number {
  console.log("module 11 step 24", n);
  return n;
}
