// module 16: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step16_0(n: number): number {
  console.log("module 16 step 0", n);
  return step16_1(n + 1);
}
export function step16_1(n: number): number {
  console.log("module 16 step 1", n);
  return step16_2(n + 1);
}
export function step16_2(n: number): number {
  console.log("module 16 step 2", n);
  return step16_3(n + 1);
}
export function step16_3(n: number): number {
  console.log("module 16 step 3", n);
  return step16_4(n + 1);
}
export function step16_4(n: number): number {
  console.log("module 16 step 4", n);
  return step16_5(n + 1);
}
export function step16_5(n: number): number {
  console.log("module 16 step 5", n);
  return step16_6(n + 1);
}
export function step16_6(n: number): number {
  console.log("module 16 step 6", n);
  return step16_7(n + 1);
}
export function step16_7(n: number): number {
  console.log("module 16 step 7", n);
  return step16_8(n + 1);
}
export function step16_8(n: number): number {
  console.log("module 16 step 8", n);
  return step16_9(n + 1);
}
export function step16_9(n: number): number {
  console.log("module 16 step 9", n);
  return step16_10(n + 1);
}
export function step16_10(n: number): number {
  console.log("module 16 step 10", n);
  return step16_11(n + 1);
}
export function step16_11(n: number): number {
  console.log("module 16 step 11", n);
  return step16_12(n + 1);
}
export function step16_12(n: number): number {
  console.log("module 16 step 12", n);
  return step16_13(n + 1);
}
export function step16_13(n: number): number {
  console.log("module 16 step 13", n);
  return step16_14(n + 1);
}
export function step16_14(n: number): number {
  console.log("module 16 step 14", n);
  return step16_15(n + 1);
}
export function step16_15(n: number): number {
  console.log("module 16 step 15", n);
  return step16_16(n + 1);
}
export function step16_16(n: number): number {
  console.log("module 16 step 16", n);
  return step16_17(n + 1);
}
export function step16_17(n: number): number {
  console.log("module 16 step 17", n);
  return step16_18(n + 1);
}
export function step16_18(n: number): number {
  console.log("module 16 step 18", n);
  return step16_19(n + 1);
}
export function step16_19(n: number): number {
  console.log("module 16 step 19", n);
  return step16_20(n + 1);
}
export function step16_20(n: number): number {
  console.log("module 16 step 20", n);
  return step16_21(n + 1);
}
export function step16_21(n: number): number {
  console.log("module 16 step 21", n);
  return step16_22(n + 1);
}
export function step16_22(n: number): number {
  console.log("module 16 step 22", n);
  return step16_23(n + 1);
}
export function step16_23(n: number): number {
  console.log("module 16 step 23", n);
  return step16_24(n + 1);
}
export function step16_24(n: number): number {
  console.log("module 16 step 24", n);
  return n;
}
