// module 10: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step10_0(n: number): number {
  console.log("module 10 step 0", n);
  return step10_1(n + 1);
}
export function step10_1(n: number): number {
  console.log("module 10 step 1", n);
  return step10_2(n + 1);
}
export function step10_2(n: number): number {
  console.log("module 10 step 2", n);
  return step10_3(n + 1);
}
export function step10_3(n: number): number {
  console.log("module 10 step 3", n);
  return step10_4(n + 1);
}
export function step10_4(n: number): number {
  console.log("module 10 step 4", n);
  return step10_5(n + 1);
}
export function step10_5(n: number): number {
  console.log("module 10 step 5", n);
  return step10_6(n + 1);
}
export function step10_6(n: number): number {
  console.log("module 10 step 6", n);
  return step10_7(n + 1);
}
export function step10_7(n: number): number {
  console.log("module 10 step 7", n);
  return step10_8(n + 1);
}
export function step10_8(n: number): number {
  console.log("module 10 step 8", n);
  return step10_9(n + 1);
}
export function step10_9(n: number): number {
  console.log("module 10 step 9", n);
  return step10_10(n + 1);
}
export function step10_10(n: number): number {
  console.log("module 10 step 10", n);
  return step10_11(n + 1);
}
export function step10_11(n: number): number {
  console.log("module 10 step 11", n);
  return step10_12(n + 1);
}
export function step10_12(n: number): number {
  console.log("module 10 step 12", n);
  return step10_13(n + 1);
}
export function step10_13(n: number): number {
  console.log("module 10 step 13", n);
  return step10_14(n + 1);
}
export function step10_14(n: number): number {
  console.log("module 10 step 14", n);
  return step10_15(n + 1);
}
export function step10_15(n: number): number {
  console.log("module 10 step 15", n);
  return step10_16(n + 1);
}
export function step10_16(n: number): number {
  console.log("module 10 step 16", n);
  return step10_17(n + 1);
}
export function step10_17(n: number): number {
  console.log("module 10 step 17", n);
  return step10_18(n + 1);
}
export function step10_18(n: number): number {
  console.log("module 10 step 18", n);
  return step10_19(n + 1);
}
export function step10_19(n: number): number {
  console.log("module 10 step 19", n);
  return step10_20(n + 1);
}
export function step10_20(n: number): number {
  console.log("module 10 step 20", n);
  return step10_21(n + 1);
}
export function step10_21(n: number): number {
  console.log("module 10 step 21", n);
  return step10_22(n + 1);
}
export function step10_22(n: number): number {
  console.log("module 10 step 22", n);
  return step10_23(n + 1);
}
export function step10_23(n: number): number {
  console.log("module 10 step 23", n);
  return step10_24(n + 1);
}
export function step10_24(n: number): number {
  console.log("module 10 step 24", n);
  return n;
}
