// module 1: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step1_0(n: number): number {
  console.log("module 1 step 0", n);
  return step1_1(n + 1);
}
export function step1_1(n: number): number {
  console.log("module 1 step 1", n);
  return step1_2(n + 1);
}
export function step1_2(n: number): number {
  console.log("module 1 step 2", n);
  return step1_3(n + 1);
}
export function step1_3(n: number): number {
  console.log("module 1 step 3", n);
  return step1_4(n + 1);
}
export function step1_4(n: number): number {
  console.log("module 1 step 4", n);
  return step1_5(n + 1);
}
export function step1_5(n: number): number {
  console.log("module 1 step 5", n);
  return step1_6(n + 1);
}
export function step1_6(n: number): number {
  console.log("module 1 step 6", n);
  return step1_7(n + 1);
}
export function step1_7(n: number): number {
  console.log("module 1 step 7", n);
  return step1_8(n + 1);
}
export function step1_8(n: number): number {
  console.log("module 1 step 8", n);
  return step1_9(n + 1);
}
export function step1_9(n: number): number {
  console.log("module 1 step 9", n);
  return step1_10(n + 1);
}
export function step1_10(n: number): number {
  console.log("module 1 step 10", n);
  return step1_11(n + 1);
}
export function step1_11(n: number): number {
  console.log("module 1 step 11", n);
  return step1_12(n + 1);
}
export function step1_12(n: number): number {
  console.log("module 1 step 12", n);
  return step1_13(n + 1);
}
export function step1_13(n: number): number {
  console.log("module 1 step 13", n);
  return step1_14(n + 1);
}
export function step1_14(n: number): number {
  console.log("module 1 step 14", n);
  return step1_15(n + 1);
}
export function step1_15(n: number): number {
  console.log("module 1 step 15", n);
  return step1_16(n + 1);
}
export function step1_16(n: number): number {
  console.log("module 1 step 16", n);
  return step1_17(n + 1);
}
export function step1_17(n: number): number {
  console.log("module 1 step 17", n);
  return step1_18(n + 1);
}
export function step1_18(n: number): number {
  console.log("module 1 step 18", n);
  return step1_19(n + 1);
}
export function step1_19(n: number): number {
  console.log("module 1 step 19", n);
  return step1_20(n + 1);
}
export function step1_20(n: number): number {
  console.log("module 1 step 20", n);
  return step1_21(n + 1);
}
export function step1_21(n: number): number {
  console.log("module 1 step 21", n);
  return step1_22(n + 1);
}
export function step1_22(n: number): number {
  console.log("module 1 step 22", n);
  return step1_23(n + 1);
}
export function step1_23(n: number): number {
  console.log("module 1 step 23", n);
  return step1_24(n + 1);
}
export function step1_24(n: number): number {
  console.log("module 1 step 24", n);
  return n;
}
