// module 15: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step15_0(n: number): number {
  console.log("module 15 step 0", n);
  return step15_1(n + 1);
}
export function step15_1(n: number): number {
  console.log("module 15 step 1", n);
  return step15_2(n + 1);
}
export function step15_2(n: number): number {
  console.log("module 15 step 2", n);
  return step15_3(n + 1);
}
export function step15_3(n: number): number {
  console.log("module 15 step 3", n);
  return step15_4(n + 1);
}
export function step15_4(n: number): number {
  console.log("module 15 step 4", n);
  return step15_5(n + 1);
}
export function step15_5(n: number): number {
  console.log("module 15 step 5", n);
  return step15_6(n + 1);
}
export function step15_6(n: number): number {
  console.log("module 15 step 6", n);
  return step15_7(n + 1);
}
export function step15_7(n: number): number {
  console.log("module 15 step 7", n);
  return step15_8(n + 1);
}
export function step15_8(n: number): number {
  console.log("module 15 step 8", n);
  return step15_9(n + 1);
}
export function step15_9(n: number): number {
  console.log("module 15 step 9", n);
  return step15_10(n + 1);
}
export function step15_10(n: number): number {
  console.log("module 15 step 10", n);
  return step15_11(n + 1);
}
export function step15_11(n: number): number {
  console.log("module 15 step 11", n);
  return step15_12(n + 1);
}
export function step15_12(n: number): number {
  console.log("module 15 step 12", n);
  return step15_13(n + 1);
}
export function step15_13(n: number): number {
  console.log("module 15 step 13", n);
  return step15_14(n + 1);
}
export function step15_14(n: number): number {
  console.log("module 15 step 14", n);
  return step15_15(n + 1);
}
export function step15_15(n: number): number {
  console.log("module 15 step 15", n);
  return step15_16(n + 1);
}
export function step15_16(n: number): number {
  console.log("module 15 step 16", n);
  return step15_17(n + 1);
}
export function step15_17(n: number): number {
  console.log("module 15 step 17", n);
  return step15_18(n + 1);
}
export function step15_18(n: number): number {
  console.log("module 15 step 18", n);
  return step15_19(n + 1);
}
export function step15_19(n: number): number {
  console.log("module 15 step 19", n);
  return step15_20(n + 1);
}
export function step15_20(n: number): number {
  console.log("module 15 step 20", n);
  return step15_21(n + 1);
}
export function step15_21(n: number): number {
  console.log("module 15 step 21", n);
  return step15_22(n + 1);
}
export function step15_22(n: number): number {
  console.log("module 15 step 22", n);
  return step15_23(n + 1);
}
export function step15_23(n: number): number {
  console.log("module 15 step 23", n);
  return step15_24(n + 1);
}
export function step15_24(n: number): number {
  console.log("module 15 step 24", n);
  return n;
}
