// module 14: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step14_0(n: number): number {
  console.log("module 14 step 0", n);
  return step14_1(n + 1);
}
export function step14_1(n: number): number {
  console.log("module 14 step 1", n);
  return step14_2(n + 1);
}
export function step14_2(n: number): number {
  console.log("module 14 step 2", n);
  return step14_3(n + 1);
}
export function step14_3(n: number): number {
  console.log("module 14 step 3", n);
  return step14_4(n + 1);
}
export function step14_4(n: number): number {
  console.log("module 14 step 4", n);
  return step14_5(n + 1);
}
export function step14_5(n: number): number {
  console.log("module 14 step 5", n);
  return step14_6(n + 1);
}
export function step14_6(n: number): number {
  console.log("module 14 step 6", n);
  return step14_7(n + 1);
}
export function step14_7(n: number): number {
  console.log("module 14 step 7", n);
  return step14_8(n + 1);
}
export function step14_8(n: number): number {
  console.log("module 14 step 8", n);
  return step14_9(n + 1);
}
export function step14_9(n: number): number {
  console.log("module 14 step 9", n);
  return step14_10(n + 1);
}
export function step14_10(n: number): number {
  console.log("module 14 step 10", n);
  return step14_11(n + 1);
}
export function step14_11(n: number): number {
  console.log("module 14 step 11", n);
  return step14_12(n + 1);
}
export function step14_12(n: number): number {
  console.log("module 14 step 12", n);
  return step14_13(n + 1);
}
export function step14_13(n: number): number {
  console.log("module 14 step 13", n);
  return step14_14(n + 1);
}
export function step14_14(n: number): number {
  console.log("module 14 step 14", n);
  return step14_15(n + 1);
}
export function step14_15(n: number): number {
  console.log("module 14 step 15", n);
  return step14_16(n + 1);
}
export function step14_16(n: number): number {
  console.log("module 14 step 16", n);
  return step14_17(n + 1);
}
export function step14_17(n: number): number {
  console.log("module 14 step 17", n);
  return step14_18(n + 1);
}
export function step14_18(n: number): number {
  console.log("module 14 step 18", n);
  return step14_19(n + 1);
}
export function step14_19(n: number): number {
  console.log("module 14 step 19", n);
  return step14_20(n + 1);
}
export function step14_20(n: number): number {
  console.log("module 14 step 20", n);
  return step14_21(n + 1);
}
export function step14_21(n: number): number {
  console.log("module 14 step 21", n);
  return step14_22(n + 1);
}
export function step14_22(n: number): number {
  console.log("module 14 step 22", n);
  return step14_23(n + 1);
}
export function step14_23(n: number): number {
  console.log("module 14 step 23", n);
  return step14_24(n + 1);
}
export function step14_24(n: number): number {
  console.log("module 14 step 24", n);
  return n;
}
