// module 13: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step13_0(n: number): number {
  console.log("module 13 step 0", n);
  return step13_1(n + 1);
}
export function step13_1(n: number): number {
  console.log("module 13 step 1", n);
  return step13_2(n + 1);
}
export function step13_2(n: number): number {
  console.log("module 13 step 2", n);
  return step13_3(n + 1);
}
export function step13_3(n: number): number {
  console.log("module 13 step 3", n);
  return step13_4(n + 1);
}
export function step13_4(n: number): number {
  console.log("module 13 step 4", n);
  return step13_5(n + 1);
}
export function step13_5(n: number): number {
  console.log("module 13 step 5", n);
  return step13_6(n + 1);
}
export function step13_6(n: number): number {
  console.log("module 13 step 6", n);
  return step13_7(n + 1);
}
export function step13_7(n: number): number {
  console.log("module 13 step 7", n);
  return step13_8(n + 1);
}
export function step13_8(n: number): number {
  console.log("module 13 step 8", n);
  return step13_9(n + 1);
}
export function step13_9(n: number): number {
  console.log("module 13 step 9", n);
  return step13_10(n + 1);
}
export function step13_10(n: number): number {
  console.log("module 13 step 10", n);
  return step13_11(n + 1);
}
export function step13_11(n: number): number {
  console.log("module 13 step 11", n);
  return step13_12(n + 1);
}
export function step13_12(n: number): number {
  console.log("module 13 step 12", n);
  return step13_13(n + 1);
}
export function step13_13(n: number): number {
  console.log("module 13 step 13", n);
  return step13_14(n + 1);
}
export function step13_14(n: number): number {
  console.log("module 13 step 14", n);
  return step13_15(n + 1);
}
export function step13_15(n: number): number {
  console.log("module 13 step 15", n);
  return step13_16(n + 1);
}
export function step13_16(n: number): number {
  console.log("module 13 step 16", n);
  return step13_17(n + 1);
}
export function step13_17(n: number): number {
  console.log("module 13 step 17", n);
  return step13_18(n + 1);
}
export function step13_18(n: number): number {
  console.log("module 13 step 18", n);
  return step13_19(n + 1);
}
export function step13_19(n: number): number {
  console.log("module 13 step 19", n);
  return step13_20(n + 1);
}
export function step13_20(n: number): number {
  console.log("module 13 step 20", n);
  return step13_21(n + 1);
}
export function step13_21(n: number): number {
  console.log("module 13 step 21", n);
  return step13_22(n + 1);
}
export function step13_22(n: number): number {
  console.log("module 13 step 22", n);
  return step13_23(n + 1);
}
export function step13_23(n: number): number {
  console.log("module 13 step 23", n);
  return step13_24(n + 1);
}
export function step13_24(n: number): number {
  console.log("module 13 step 24", n);
  return n;
}
