// module 18: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step18_0(n: number): number {
  console.log("module 18 step 0", n);
  return step18_1(n + 1);
}
export function step18_1(n: number): number {
  console.log("module 18 step 1", n);
  return step18_2(n + 1);
}
export function step18_2(n: number): number {
  console.log("module 18 step 2", n);
  return step18_3(n + 1);
}
export function step18_3(n: number): number {
  console.log("module 18 step 3", n);
  return step18_4(n + 1);
}
export function step18_4(n: number): number {
  console.log("module 18 step 4", n);
  return step18_5(n + 1);
}
export function step18_5(n: number): number {
  console.log("module 18 step 5", n);
  return step18_6(n + 1);
}
export function step18_6(n: number): number {
  console.log("module 18 step 6", n);
  return step18_7(n + 1);
}
export function step18_7(n: number): number {
  console.log("module 18 step 7", n);
  return step18_8(n + 1);
}
export function step18_8(n: number): number {
  console.log("module 18 step 8", n);
  return step18_9(n + 1);
}
export function step18_9(n: number): number {
  console.log("module 18 step 9", n);
  return step18_10(n + 1);
}
export function step18_10(n: number): number {
  console.log("module 18 step 10", n);
  return step18_11(n + 1);
}
export function step18_11(n: number): number {
  console.log("module 18 step 11", n);
  return step18_12(n + 1);
}
export function step18_12(n: number): number {
  console.log("module 18 step 12", n);
  return step18_13(n + 1);
}
export function step18_13(n: number): number {
  console.log("module 18 step 13", n);
  return step18_14(n + 1);
}
export function step18_14(n: number): number {
  console.log("module 18 step 14", n);
  return step18_15(n + 1);
}
export function step18_15(n: number): number {
  console.log("module 18 step 15", n);
  return step18_16(n + 1);
}
export function step18_16(n: number): number {
  console.log("module 18 step 16", n);
  return step18_17(n + 1);
}
export function step18_17(n: number): number {
  console.log("module 18 step 17", n);
  return step18_18(n + 1);
}
export function step18_18(n: number): number {
  console.log("module 18 step 18", n);
  return step18_19(n + 1);
}
export function step18_19(n: number): number {
  console.log("module 18 step 19", n);
  return step18_20(n + 1);
}
export function step18_20(n: number): number {
  console.log("module 18 step 20", n);
  return step18_21(n + 1);
}
export function step18_21(n: number): number {
  console.log("module 18 step 21", n);
  return step18_22(n + 1);
}
export function step18_22(n: number): number {
  console.log("module 18 step 22", n);
  return step18_23(n + 1);
}
export function step18_23(n: number): number {
  console.log("module 18 step 23", n);
  return step18_24(n + 1);
}
export function step18_24(n: number): number {
  console.log("module 18 step 24", n);
  return n;
}
