// module 12: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step12_0(n: number): number {
  console.log("module 12 step 0", n);
  return step12_1(n + 1);
}
export function step12_1(n: number): number {
  console.log("module 12 step 1", n);
  return step12_2(n + 1);
}
export function step12_2(n: number): number {
  console.log("module 12 step 2", n);
  return step12_3(n + 1);
}
export function step12_3(n: number): number {
  console.log("module 12 step 3", n);
  return step12_4(n + 1);
}
export function step12_4(n: number): number {
  console.log("module 12 step 4", n);
  return step12_5(n + 1);
}
export function step12_5(n: number): number {
  console.log("module 12 step 5", n);
  return step12_6(n + 1);
}
export function step12_6(n: number): number {
  console.log("module 12 step 6", n);
  return step12_7(n + 1);
}
export function step12_7(n: number): number {
  console.log("module 12 step 7", n);
  return step12_8(n + 1);
}
export function step12_8(n: number): number {
  console.log("module 12 step 8", n);
  return step12_9(n + 1);
}
export function step12_9(n: number): number {
  console.log("module 12 step 9", n);
  return step12_10(n + 1);
}
export function step12_10(n: number): number {
  console.log("module 12 step 10", n);
  return step12_11(n + 1);
}
export function step12_11(n: number): number {
  console.log("module 12 step 11", n);
  return step12_12(n + 1);
}
export function step12_12(n: number): number {
  console.log("module 12 step 12", n);
  return step12_13(n + 1);
}
export function step12_13(n: number): number {
  console.log("module 12 step 13", n);
  return step12_14(n + 1);
}
export function step12_14(n: number): number {
  console.log("module 12 step 14", n);
  return step12_15(n + 1);
}
export function step12_15(n: number): number {
  console.log("module 12 step 15", n);
  return step12_16(n + 1);
}
export function step12_16(n: number): number {
  console.log("module 12 step 16", n);
  return step12_17(n + 1);
}
export function step12_17(n: number): number {
  console.log("module 12 step 17", n);
  return step12_18(n + 1);
}
export function step12_18(n: number): number {
  console.log("module 12 step 18", n);
  return step12_19(n + 1);
}
export function step12_19(n: number): number {
  console.log("module 12 step 19", n);
  return step12_20(n + 1);
}
export function step12_20(n: number): number {
  console.log("module 12 step 20", n);
  return step12_21(n + 1);
}
export function step12_21(n: number): number {
  console.log("module 12 step 21", n);
  return step12_22(n + 1);
}
export function step12_22(n: number): number {
  console.log("module 12 step 22", n);
  return step12_23(n + 1);
}
export function step12_23(n: number): number {
  console.log("module 12 step 23", n);
  return step12_24(n + 1);
}
export function step12_24(n: number): number {
  console.log("module 12 step 24", n);
  return n;
}
