// module 17: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step17_0(n: number): number {
  console.log("module 17 step 0", n);
  return step17_1(n + 1);
}
export function step17_1(n: number): number {
  console.log("module 17 step 1", n);
  return step17_2(n + 1);
}
export function step17_2(n: number): number {
  console.log("module 17 step 2", n);
  return step17_3(n + 1);
}
export function step17_3(n: number): number {
  console.log("module 17 step 3", n);
  return step17_4(n + 1);
}
export function step17_4(n: number): number {
  console.log("module 17 step 4", n);
  return step17_5(n + 1);
}
export function step17_5(n: number): number {
  console.log("module 17 step 5", n);
  return step17_6(n + 1);
}
export function step17_6(n: number): number {
  console.log("module 17 step 6", n);
  return step17_7(n + 1);
}
export function step17_7(n: number): number {
  console.log("module 17 step 7", n);
  return step17_8(n + 1);
}
export function step17_8(n: number): number {
  console.log("module 17 step 8", n);
  return step17_9(n + 1);
}
export function step17_9(n: number): number {
  console.log("module 17 step 9", n);
  return step17_10(n + 1);
}
export function step17_10(n: number): number {
  console.log("module 17 step 10", n);
  return step17_11(n + 1);
}
export function step17_11(n: number): number {
  console.log("module 17 step 11", n);
  return step17_12(n + 1);
}
export function step17_12(n: number): number {
  console.log("module 17 step 12", n);
  return step17_13(n + 1);
}
export function step17_13(n: number): number {
  console.log("module 17 step 13", n);
  return step17_14(n + 1);
}
export function step17_14(n: number): number {
  console.log("module 17 step 14", n);
  return step17_15(n + 1);
}
export function step17_15(n: number): number {
  console.log("module 17 step 15", n);
  return step17_16(n + 1);
}
export function step17_16(n: number): number {
  console.log("module 17 step 16", n);
  return step17_17(n + 1);
}
export function step17_17(n: number): number {
  console.log("module 17 step 17", n);
  return step17_18(n + 1);
}
export function step17_18(n: number): number {
  console.log("module 17 step 18", n);
  return step17_19(n + 1);
}
export function step17_19(n: number): number {
  console.log("module 17 step 19", n);
  return step17_20(n + 1);
}
export function step17_20(n: number): number {
  console.log("module 17 step 20", n);
  return step17_21(n + 1);
}
export function step17_21(n: number): number {
  console.log("module 17 step 21", n);
  return step17_22(n + 1);
}
export function step17_22(n: number): number {
  console.log("module 17 step 22", n);
  return step17_23(n + 1);
}
export function step17_23(n: number): number {
  console.log("module 17 step 23", n);
  return step17_24(n + 1);
}
export function step17_24(n: number): number {
  console.log("module 17 step 24", n);
  return n;
}
