// module 3: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step3_0(n: number): number {
  console.log("module 3 step 0", n);
  return step3_1(n + 1);
}
export function step3_1(n: number): number {
  console.log("module 3 step 1", n);
  return step3_2(n + 1);
}
export function step3_2(n: number): number {
  console.log("module 3 step 2", n);
  return step3_3(n + 1);
}
export function step3_3(n: number): number {
  console.log("module 3 step 3", n);
  return step3_4(n + 1);
}
export function step3_4(n: number): number {
  console.log("module 3 step 4", n);
  return step3_5(n + 1);
}
export function step3_5(n: number): number {
  console.log("module 3 step 5", n);
  return step3_6(n + 1);
}
export function step3_6(n: number): number {
  console.log("module 3 step 6", n);
  return step3_7(n + 1);
}
export function step3_7(n: number): number {
  console.log("module 3 step 7", n);
  return step3_8(n + 1);
}
export function step3_8(n: number): number {
  console.log("module 3 step 8", n);
  return step3_9(n + 1);
}
export function step3_9(n: number): number {
  console.log("module 3 step 9", n);
  return step3_10(n + 1);
}
export function step3_10(n: number): number {
  console.log("module 3 step 10", n);
  return step3_11(n + 1);
}
export function step3_11(n: number): number {
  console.log("module 3 step 11", n);
  return step3_12(n + 1);
}
export function step3_12(n: number): number {
  console.log("module 3 step 12", n);
  return step3_13(n + 1);
}
export function step3_13(n: number): number {
  console.log("module 3 step 13", n);
  return step3_14(n + 1);
}
export function step3_14(n: number): number {
  console.log("module 3 step 14", n);
  return step3_15(n + 1);
}
export function step3_15(n: number): number {
  console.log("module 3 step 15", n);
  return step3_16(n + 1);
}
export function step3_16(n: number): number {
  console.log("module 3 step 16", n);
  return step3_17(n + 1);
}
export function step3_17(n: number): number {
  console.log("module 3 step 17", n);
  return step3_18(n + 1);
}
export function step3_18(n: number): number {
  console.log("module 3 step 18", n);
  return step3_19(n + 1);
}
export function step3_19(n: number): number {
  console.log("module 3 step 19", n);
  return step3_20(n + 1);
}
export function step3_20(n: number): number {
  console.log("module 3 step 20", n);
  return step3_21(n + 1);
}
export function step3_21(n: number): number {
  console.log("module 3 step 21", n);
  return step3_22(n + 1);
}
export function step3_22(n: number): number {
  console.log("module 3 step 22", n);
  return step3_23(n + 1);
}
export function step3_23(n: number): number {
  console.log("module 3 step 23", n);
  return step3_24(n + 1);
}
export function step3_24(n: number): number {
  console.log("module 3 step 24", n);
  return n;
}
