// module 4: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step4_0(n: number): number {
  console.log("module 4 step 0", n);
  return step4_1(n + 1);
}
export function step4_1(n: number): number {
  console.log("module 4 step 1", n);
  return step4_2(n + 1);
}
export function step4_2(n: number): number {
  console.log("module 4 step 2", n);
  return step4_3(n + 1);
}
export function step4_3(n: number): number {
  console.log("module 4 step 3", n);
  return step4_4(n + 1);
}
export function step4_4(n: number): number {
  console.log("module 4 step 4", n);
  return step4_5(n + 1);
}
export function step4_5(n: number): number {
  console.log("module 4 step 5", n);
  return step4_6(n + 1);
}
export function step4_6(n: number): number {
  console.log("module 4 step 6", n);
  return step4_7(n + 1);
}
export function step4_7(n: number): number {
  console.log("module 4 step 7", n);
  return step4_8(n + 1);
}
export function step4_8(n: number): number {
  console.log("module 4 step 8", n);
  return step4_9(n + 1);
}
export function step4_9(n: number): number {
  console.log("module 4 step 9", n);
  return step4_10(n + 1);
}
export function step4_10(n: number): number {
  console.log("module 4 step 10", n);
  return step4_11(n + 1);
}
export function step4_11(n: number): number {
  console.log("module 4 step 11", n);
  return step4_12(n + 1);
}
export function step4_12(n: number): number {
  console.log("module 4 step 12", n);
  return step4_13(n + 1);
}
export function step4_13(n: number): number {
  console.log("module 4 step 13", n);
  return step4_14(n + 1);
}
export function step4_14(n: number): number {
  console.log("module 4 step 14", n);
  return step4_15(n + 1);
}
export function step4_15(n: number): number {
  console.log("module 4 step 15", n);
  return step4_16(n + 1);
}
export function step4_16(n: number): number {
  console.log("module 4 step 16", n);
  return step4_17(n + 1);
}
export function step4_17(n: number): number {
  console.log("module 4 step 17", n);
  return step4_18(n + 1);
}
export function step4_18(n: number): number {
  console.log("module 4 step 18", n);
  return step4_19(n + 1);
}
export function step4_19(n: number): number {
  console.log("module 4 step 19", n);
  return step4_20(n + 1);
}
export function step4_20(n: number): number {
  console.log("module 4 step 20", n);
  return step4_21(n + 1);
}
export function step4_21(n: number): number {
  console.log("module 4 step 21", n);
  return step4_22(n + 1);
}
export function step4_22(n: number): number {
  console.log("module 4 step 22", n);
  return step4_23(n + 1);
}
export function step4_23(n: number): number {
  console.log("module 4 step 23", n);
  return step4_24(n + 1);
}
export function step4_24(n: number): number {
  console.log("module 4 step 24", n);
  return n;
}
