// module 5: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step5_0(n: number): number {
  console.log("module 5 step 0", n);
  return step5_1(n + 1);
}
export function step5_1(n: number): number {
  console.log("module 5 step 1", n);
  return step5_2(n + 1);
}
export function step5_2(n: number): number {
  console.log("module 5 step 2", n);
  return step5_3(n + 1);
}
export function step5_3(n: number): number {
  console.log("module 5 step 3", n);
  return step5_4(n + 1);
}
export function step5_4(n: number): number {
  console.log("module 5 step 4", n);
  return step5_5(n + 1);
}
export function step5_5(n: number): number {
  console.log("module 5 step 5", n);
  return step5_6(n + 1);
}
export function step5_6(n: number): number {
  console.log("module 5 step 6", n);
  return step5_7(n + 1);
}
export function step5_7(n: number): number {
  console.log("module 5 step 7", n);
  return step5_8(n + 1);
}
export function step5_8(n: number): number {
  console.log("module 5 step 8", n);
  return step5_9(n + 1);
}
export function step5_9(n: number): number {
  console.log("module 5 step 9", n);
  return step5_10(n + 1);
}
export function step5_10(n: number): number {
  console.log("module 5 step 10", n);
  return step5_11(n + 1);
}
export function step5_11(n: number): number {
  console.log("module 5 step 11", n);
  return step5_12(n + 1);
}
export function step5_12(n: number): number {
  console.log("module 5 step 12", n);
  return step5_13(n + 1);
}
export function step5_13(n: number): number {
  console.log("module 5 step 13", n);
  return step5_14(n + 1);
}
export function step5_14(n: number): number {
  console.log("module 5 step 14", n);
  return step5_15(n + 1);
}
export function step5_15(n: number): number {
  console.log("module 5 step 15", n);
  return step5_16(n + 1);
}
export function step5_16(n: number): number {
  console.log("module 5 step 16", n);
  return step5_17(n + 1);
}
export function step5_17(n: number): number {
  console.log("module 5 step 17", n);
  return step5_18(n + 1);
}
export function step5_18(n: number): number {
  console.log("module 5 step 18", n);
  return step5_19(n + 1);
}
export function step5_19(n: number): number {
  console.log("module 5 step 19", n);
  return step5_20(n + 1);
}
export function step5_20(n: number): number {
  console.log("module 5 step 20", n);
  return step5_21(n + 1);
}
export function step5_21(n: number): number {
  console.log("module 5 step 21", n);
  return step5_22(n + 1);
}
export function step5_22(n: number): number {
  console.log("module 5 step 22", n);
  return step5_23(n + 1);
}
export function step5_23(n: number): number {
  console.log("module 5 step 23", n);
  return step5_24(n + 1);
}
export function step5_24(n: number): number {
  console.log("module 5 step 24", n);
  return n;
}
