// module 6: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step6_0(n: number): number {
  console.log("module 6 step 0", n);
  return step6_1(n + 1);
}
export function step6_1(n: number): number {
  console.log("module 6 step 1", n);
  return step6_2(n + 1);
}
export function step6_2(n: number): number {
  console.log("module 6 step 2", n);
  return step6_3(n + 1);
}
export function step6_3(n: number): number {
  console.log("module 6 step 3", n);
  return step6_4(n + 1);
}
export function step6_4(n: number): number {
  console.log("module 6 step 4", n);
  return step6_5(n + 1);
}
export function step6_5(n: number): number {
  console.log("module 6 step 5", n);
  return step6_6(n + 1);
}
export function step6_6(n: number): number {
  console.log("module 6 step 6", n);
  return step6_7(n + 1);
}
export function step6_7(n: number): number {
  console.log("module 6 step 7", n);
  return step6_8(n + 1);
}
export function step6_8(n: number): number {
  console.log("module 6 step 8", n);
  return step6_9(n + 1);
}
export function step6_9(n: number): number {
  console.log("module 6 step 9", n);
  return step6_10(n + 1);
}
export function step6_10(n: number): number {
  console.log("module 6 step 10", n);
  return step6_11(n + 1);
}
export function step6_11(n: number): number {
  console.log("module 6 step 11", n);
  return step6_12(n + 1);
}
export function step6_12(n: number): number {
  console.log("module 6 step 12", n);
  return step6_13(n + 1);
}
export function step6_13(n: number): number {
  console.log("module 6 step 13", n);
  return step6_14(n + 1);
}
export function step6_14(n: number): number {
  console.log("module 6 step 14", n);
  return step6_15(n + 1);
}
export function step6_15(n: number): number {
  console.log("module 6 step 15", n);
  return step6_16(n + 1);
}
export function step6_16(n: number): number {
  console.log("module 6 step 16", n);
  return step6_17(n + 1);
}
export function step6_17(n: number): number {
  console.log("module 6 step 17", n);
  return step6_18(n + 1);
}
export function step6_18(n: number): number {
  console.log("module 6 step 18", n);
  return step6_19(n + 1);
}
export function step6_19(n: number): number {
  console.log("module 6 step 19", n);
  return step6_20(n + 1);
}
export function step6_20(n: number): number {
  console.log("module 6 step 20", n);
  return step6_21(n + 1);
}
export function step6_21(n: number): number {
  console.log("module 6 step 21", n);
  return step6_22(n + 1);
}
export function step6_22(n: number): number {
  console.log("module 6 step 22", n);
  return step6_23(n + 1);
}
export function step6_23(n: number): number {
  console.log("module 6 step 23", n);
  return step6_24(n + 1);
}
export function step6_24(n: number): number {
  console.log("module 6 step 24", n);
  return n;
}
