// module 8: a chain of 25 steps (generated by scripts/gen_big_thread.mjs)
export function step8_0(n: number): number {
  console.log("module 8 step 0", n);
  return step8_1(n + 1);
}
export function step8_1(n: number): number {
  console.log("module 8 step 1", n);
  return step8_2(n + 1);
}
export function step8_2(n: number): number {
  console.log("module 8 step 2", n);
  return step8_3(n + 1);
}
export function step8_3(n: number): number {
  console.log("module 8 step 3", n);
  return step8_4(n + 1);
}
export function step8_4(n: number): number {
  console.log("module 8 step 4", n);
  return step8_5(n + 1);
}
export function step8_5(n: number): number {
  console.log("module 8 step 5", n);
  return step8_6(n + 1);
}
export function step8_6(n: number): number {
  console.log("module 8 step 6", n);
  return step8_7(n + 1);
}
export function step8_7(n: number): number {
  console.log("module 8 step 7", n);
  return step8_8(n + 1);
}
export function step8_8(n: number): number {
  console.log("module 8 step 8", n);
  return step8_9(n + 1);
}
export function step8_9(n: number): number {
  console.log("module 8 step 9", n);
  return step8_10(n + 1);
}
export function step8_10(n: number): number {
  console.log("module 8 step 10", n);
  return step8_11(n + 1);
}
export function step8_11(n: number): number {
  console.log("module 8 step 11", n);
  return step8_12(n + 1);
}
export function step8_12(n: number): number {
  console.log("module 8 step 12", n);
  return step8_13(n + 1);
}
export function step8_13(n: number): number {
  console.log("module 8 step 13", n);
  return step8_14(n + 1);
}
export function step8_14(n: number): number {
  console.log("module 8 step 14", n);
  return step8_15(n + 1);
}
export function step8_15(n: number): number {
  console.log("module 8 step 15", n);
  return step8_16(n + 1);
}
export function step8_16(n: number): number {
  console.log("module 8 step 16", n);
  return step8_17(n + 1);
}
export function step8_17(n: number): number {
  console.log("module 8 step 17", n);
  return step8_18(n + 1);
}
export function step8_18(n: number): number {
  console.log("module 8 step 18", n);
  return step8_19(n + 1);
}
export function step8_19(n: number): number {
  console.log("module 8 step 19", n);
  return step8_20(n + 1);
}
export function step8_20(n: number): number {
  console.log("module 8 step 20", n);
  return step8_21(n + 1);
}
export function step8_21(n: number): number {
  console.log("module 8 step 21", n);
  return step8_22(n + 1);
}
export function step8_22(n: number): number {
  console.log("module 8 step 22", n);
  return step8_23(n + 1);
}
export function step8_23(n: number): number {
  console.log("module 8 step 23", n);
  return step8_24(n + 1);
}
export function step8_24(n: number): number {
  console.log("module 8 step 24", n);
  return n;
}
