// Quality layer, wiring: which verbs may GATE (reject a packet) and which
// are advisory. standings.json is GENERATED by
// `scripts/quality_calibrate.mjs --status --write` from the calibration
// records (M-TABLES precedent: generated at build time, never probed at
// run time). The three M-GRAMMAR verbs gate as they always have. A Run 1
// verb gates only when its record reads MAY-GATE; everything else
// (CANDIDATE, DEMOTE, STALE, RETIRE, ADVISORY) is advisory: a `violated`
// becomes a recorded line, never a reject.
//
// IMPORTED, not read from disk. The first cut located the file beside this
// module through import.meta.url; the esbuild CJS bundle (dist/server.js)
// has no import.meta.url, the read threw, the catch made it null, and every
// Run 1 verb was silently advisory in the BUILT server while the source
// path — and every unit test — gated correctly. Head-to-head #3's arm A
// (2026-09-21) showed it: a `violated` not-in-loop fact printed as
// "ADVISORY (never rejects; uncalibrated or demoted verb)". A JSON import
// is bundled by esbuild and loaded by Node's strip-types alike, so the two
// paths cannot disagree.

import standingsJson from "./standings.json" with { type: "json" };

/** A ratified calibration record, as reviews/quality-layer/calibration/
 *  holds it and quality_model.json's CalibrationRecord defines it. Carried
 *  here so a DERIVED dimension can be gate-blocking without the deriver
 *  reading reviews/ at derive time. */
export type CalibrationRecord = { commit: string } & Record<string, unknown>;

export interface Standings {
  generatedAt: string;
  commit: string;
  verbs: Record<string, string>;
  /** The record behind each MAY-GATE verb. Absent for anything advisory. */
  records?: Record<string, CalibrationRecord>;
}

const LIVE_GRAMMAR = new Set(["callers-only", "import-only", "calls-through"]);
const FILE: Standings | null =
  standingsJson && typeof standingsJson === "object" && (standingsJson as Standings).verbs && typeof (standingsJson as Standings).verbs === "object"
    ? (standingsJson as Standings)
    : null;
let override: Standings | null | undefined;

export function loadStandings(): Standings | null {
  return override === undefined ? FILE : override;
}

/** For tests: replace the generated standings (null = no standings at all), or forget an override. */
export function setStandingsForTest(s: Standings | null | undefined): void { override = s; }

/** For tests: forget any override (the generated file is immutable at run time). */
export function resetStandings(): void { override = undefined; }

export function verbMayGate(rule: string): boolean {
  if (LIVE_GRAMMAR.has(rule)) return true;
  return loadStandings()?.verbs[rule] === "MAY-GATE";
}

/**
 * The ratified calibration record behind a verb, or null when it has none.
 *
 * What it entitles: a quality-model dimension may be `gate-blocking` only
 * with a record beside it (quality_model.json's if/then). That rule is what
 * kept every DERIVED dimension advisory through Run 2 and Run 3 — no verb
 * had earned a standing yet — and it is what lets them gate now that four
 * have. The record rides the generated standings rather than being read
 * from reviews/ at derive time: the deriver runs inside the server, and the
 * server must not probe the repository it is analysing FROM.
 */
export function calibrationRecordFor(rule: string): CalibrationRecord | null {
  if (!verbMayGate(rule)) return null;
  const rec = loadStandings()?.records?.[rule];
  return rec && typeof rec.commit === "string" ? rec : null;
}

/** The Run 1 verbs whose calibration record reads MAY-GATE. */
export function calibratedVerbs(): Set<string> {
  const s = loadStandings();
  return new Set(Object.entries(s?.verbs ?? {}).filter(([, v]) => v === "MAY-GATE").map(([k]) => k));
}
