#!/usr/bin/env node
// M-TABLES — GENERATE the standard-library tables instead of typing them.
//
// M-STACK's evidence tables were hand-written, and a hand-written stdlib
// list is not merely incomplete: `classifyTool` has no way to say "I do
// not know", so an unlisted module is stamped `origin: "third-party"` —
// a positive claim that the project depends on something it does not.
// PYTHON_STDLIB held 87 of the 192 roots a real interpreter reports, so
// 105 standard modules would have been reported as dependencies.
//
// Every runtime here can be ASKED, which makes the answer evidence
// rather than recollection:
//
//   python   sys.stdlib_module_names  +  dir(builtins)
//   node     module.builtinModules
//   bash     compgen -b
//
// GENERATED AT BUILD TIME, COMMITTED — never probed while parsing. The
// tree-sitter WASM precedent: a pinned artefact is reproducible, reviewable
// in a diff, and identical on every machine. Probing at parse time would
// make the IR depend on the analysing laptop (a deploy script's `aws`
// resolves differently on a server than here) and would execute something
// on every parse, which is the effect-consent floor's business.
//
// Usage:
//   node scripts/gen_stack_tables.mjs           # write the table
//   node scripts/gen_stack_tables.mjs --check   # fail if it has drifted
import { execFileSync } from "node:child_process";
import { builtinModules } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "shared", "stack_stdlib.generated.ts");

/** Modules that WERE the standard library and were later removed (PEP 594's
 *  "dead batteries", plus the 3.12 removals). A project on an older
 *  interpreter imports these legitimately, and the current interpreter can
 *  no longer report them — so a version-stamped list alone would call
 *  `distutils` a third-party dependency. Closed historical fact, not an
 *  open-ended list: nothing is ever ADDED to the standard library's past. */
const PYTHON_REMOVED = [
  "aifc", "asynchat", "asyncore", "audioop", "binhex", "cgi", "cgitb",
  "chunk", "crypt", "distutils", "formatter", "imghdr", "imp", "lib2to3",
  "macpath", "mailcap", "msilib", "nis", "nntplib", "ossaudiodev", "parser",
  "pipes", "smtpd", "sndhdr", "spwd", "sunau", "symbol", "telnetlib", "uu",
  "xdrlib",
];

function py(expr) {
  return execFileSync("python3", ["-c", expr], { encoding: "utf8" }).trim();
}

function collect() {
  const pythonVersion = py("import sys; print('.'.join(map(str, sys.version_info[:3])))");
  const stdlib = py(
    "import sys; print('\\n'.join(sorted(n for n in sys.stdlib_module_names if not n.startswith('_'))))",
  ).split("\n");
  // Callables only: `True`/`Ellipsis`/`__debug__` are never a call head, and
  // `__import__` is deliberately excluded — a dynamic import IS a boundary.
  const builtins = py(
    "import builtins; print('\\n'.join(sorted(n for n in dir(builtins)"
    + " if not n.startswith('_') and callable(getattr(builtins, n)))))",
  ).split("\n");

  const nodeVersion = process.versions.node;
  const node = [...new Set(
    builtinModules.filter((m) => !m.startsWith("_")).map((m) => (m.startsWith("node:") ? m.slice(5) : m)),
  )].filter((m) => !m.includes("/")).sort();

  const bashVersion = execFileSync("bash", ["-c", "echo $BASH_VERSION"], { encoding: "utf8" }).trim();
  const bashBuiltins = execFileSync("bash", ["-c", "compgen -b"], { encoding: "utf8" })
    .trim().split("\n").sort();
  // A KEYWORD is not a builtin: the shell PARSES `[[` and `for` rather than
  // running them. Different fact, asked with a different flag.
  const bashKeywords = execFileSync("bash", ["-c", "compgen -k"], { encoding: "utf8" })
    .trim().split("\n").sort();

  return {
    pythonVersion, stdlib, builtins, nodeVersion, node,
    bashVersion, bashBuiltins, bashKeywords,
  };
}

/** Deterministic formatting: sorted input, wrapped at a fixed column, so
 *  regenerating on the same runtimes is byte-identical or it is drift. */
function block(names) {
  const lines = [];
  let line = "";
  for (const n of names) {
    const piece = `"${n}",`;
    if (line && `${line} ${piece}`.length > 76) { lines.push(`  ${line}`); line = piece; }
    else line = line ? `${line} ${piece}` : piece;
  }
  if (line) lines.push(`  ${line}`);
  return lines.join("\n");
}

function render(d) {
  return `// GENERATED by scripts/gen_stack_tables.mjs — DO NOT EDIT BY HAND.
//
// The standard library of each language, asked of the language itself
// rather than remembered. Regenerate with:
//
//   node scripts/gen_stack_tables.mjs
//
// \`npm run test:stack-tables\` fails if this file has drifted from what
// the runtimes report, so the tables cannot quietly rot the way the
// hand-written ones did (87 of Python's 192 stdlib roots, which made
// \`origin: "third-party"\` a false claim about 105 standard modules).
//
// A version stamp is not decoration: \`sys.stdlib_module_names\` describes
// ONE interpreter version. PYTHON_STDLIB_REMOVED carries the modules that
// used to be standard so an older project is not accused of a dependency.

export const GENERATED_FROM = {
  python: ${JSON.stringify(d.pythonVersion)},
  node: ${JSON.stringify(d.nodeVersion)},
  bash: ${JSON.stringify(d.bashVersion)},
} as const;

/** \`sys.stdlib_module_names\` — every module this Python ships, complete. */
export const PYTHON_STDLIB_CURRENT: readonly string[] = [
${block(d.stdlib)}
];

/** Modules removed from the standard library (PEP 594 + the 3.12 cuts). A
 *  project on an older interpreter imports these legitimately. */
export const PYTHON_STDLIB_REMOVED: readonly string[] = [
${block(PYTHON_REMOVED)}
];

/** \`dir(builtins)\`, callables only — every name Python resolves without an
 *  import, INCLUDING every exception constructor (a \`raise ValueError(...)\`
 *  is a call node, and before M-RESOLVE one inside a funnel briefly read as
 *  a subprocess round trip). */
export const PYTHON_BUILTIN_NAMES: readonly string[] = [
${block(d.builtins)}
];

/** \`module.builtinModules\`, \`node:\` prefix stripped. */
export const NODE_BUILTIN_NAMES: readonly string[] = [
${block(d.node)}
];

/** \`compgen -b\` — the shell's OWN builtins, and nothing else. What bash
 *  scripts mostly call is external binaries, and no list can enumerate
 *  those: \`command -v\` would answer for the analysing machine, not the
 *  host the script deploys to. Coreutils plumbing is a separate, curated
 *  list in stack_taxonomy.ts; anything in neither is \`origin: "unknown"\`. */
export const BASH_SHELL_BUILTIN_NAMES: readonly string[] = [
${block(d.bashBuiltins)}
];

/** \`compgen -k\` — the shell's reserved words. Parsed, never executed, so
 *  never a tool and never a dependency. */
export const BASH_KEYWORD_NAMES: readonly string[] = [
${block(d.bashKeywords)}
];
`;
}

const check = process.argv.includes("--check");
const text = render(collect());
if (check) {
  let current = "";
  try { current = readFileSync(OUT, "utf8"); } catch { /* missing = drift */ }
  if (current !== text) {
    console.error(
      "stack_stdlib.generated.ts has DRIFTED from what the runtimes report.\n"
      + "Run: node scripts/gen_stack_tables.mjs",
    );
    process.exit(1);
  }
  console.log("stack_stdlib.generated.ts is current.");
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT}`);
}
