#!/usr/bin/env node
// Generates test/fixtures/big_thread: a TypeScript project whose one entry
// script walks 20 modules x 25 functions — a thread of 500+ steps, above the
// thread view's fold threshold (thread_fold.ts FOLD_ABOVE = 400). Committed
// output; re-run only to change the shape:  node scripts/gen_big_thread.mjs
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = join(dirname(dirname(fileURLToPath(import.meta.url))), 'test/fixtures/big_thread');
const MODS = 20, FNS = 25;
rmSync(ROOT, { recursive: true, force: true });
mkdirSync(join(ROOT, 'src'), { recursive: true });
writeFileSync(join(ROOT, 'package.json'), JSON.stringify({ name: 'big-thread-fixture', private: true, type: 'module' }, null, 2) + '\n');
for (let m = 0; m < MODS; m++) {
  const L = [`// module ${m}: a chain of ${FNS} steps (generated by scripts/gen_big_thread.mjs)`];
  for (let f = 0; f < FNS; f++) {
    const next = f + 1 < FNS ? `  return step${m}_${f + 1}(n + 1);` : '  return n;';
    L.push(`export function step${m}_${f}(n: number): number {`, `  console.log("module ${m} step ${f}", n);`, next, '}');
  }
  writeFileSync(join(ROOT, 'src', `mod${m}.ts`), L.join('\n') + '\n');
}
const imports = Array.from({ length: MODS }, (_, m) => `import { step${m}_0 } from "./src/mod${m}";`);
const calls = Array.from({ length: MODS }, (_, m) => `  total += step${m}_0(${m});`);
writeFileSync(join(ROOT, 'run.ts'), ['#!/usr/bin/env node', ...imports, '', 'function main(): void {', '  let total = 0;', ...calls, '  console.log(total);', '}', '', 'main();', ''].join('\n'));
console.log(`wrote ${MODS} modules x ${FNS} functions + run.ts to ${ROOT}`);
