#!/usr/bin/env bash
# M-LANG2a — regenerate the bash frontend's committed snapshot:
#   test/fixtures/bash/deploy_demo/deploy_demo.ir.json
# (linked file-map shape, mirroring flask_demo.ir.json). Per the
# vibegraph-fixtures contract: snapshots are regenerated by THIS script
# against current frontend output, never hand-edited.
set -euo pipefail
cd "$(dirname "$0")/.."

FIXTURE=test/fixtures/bash/deploy_demo
OUT="$FIXTURE/deploy_demo.ir.json"

(cd "$FIXTURE" && printf 'deploy.sh\tdeploy.sh\nlib/common.sh\tlib/common.sh\n' \
  | node ../../../../scripts/frontends/bash/parse_bash.mjs --batch) \
  | node -e '
    let raw = "";
    process.stdin.setEncoding("utf-8");
    process.stdin.on("data", (c) => (raw += c));
    process.stdin.on("end", () => {
      const { files, errors } = JSON.parse(raw);
      if (Object.keys(errors ?? {}).length) {
        console.error("regen_bash: parse errors:", JSON.stringify(errors));
        process.exit(1);
      }
      process.stdout.write(JSON.stringify({ files }));
    });' \
  | node scripts/frontends/bash/link_bash.mjs \
  | node -e '
    let raw = "";
    process.stdin.setEncoding("utf-8");
    process.stdin.on("data", (c) => (raw += c));
    process.stdin.on("end", () => {
      const { files } = JSON.parse(raw);
      process.stdout.write(JSON.stringify(files, null, 2) + "\n");
    });' > "$OUT"

node scripts/validate_ir.mjs "$OUT"
echo "regenerated $OUT"

# M-LANG2b — the thread snapshot: seed deploy.sh:main through
# extract_thread.py (the SAME extractor as Python; its non-python
# branch classifies via frontend-stamped effectKind).
THREAD_OUT="$FIXTURE/deploy_demo.thread.json"
node -e '
  const files = require("./'"$OUT"'");
  process.stdout.write(JSON.stringify({
    files,
    seeds: [{ seedFile: "deploy.sh", seedId: "module/main.fn", entryPointId: "deploy.sh:main" }],
  }));' \
  | PYTHONPATH=.pydeps python3 scripts/extract_thread.py --batch-seeds \
  | node -e '
    let raw = "";
    process.stdin.setEncoding("utf-8");
    process.stdin.on("data", (c) => (raw += c));
    process.stdin.on("end", () => {
      process.stdout.write(JSON.stringify(JSON.parse(raw), null, 2) + "\n");
    });' > "$THREAD_OUT"
echo "regenerated $THREAD_OUT"
