#!/usr/bin/env node
// M-CONTRACT.1 — regenerate the POLYGLOT fixture's committed envelope:
//   test/fixtures/polyglot/shop_demo/shop_demo.project.json
//
// Mirrors server.ts's directory pipeline EXACTLY, per language, off the
// SAME registry the server dispatches through (src/server/languages.ts):
//   walk (registered extensions only) → one batch parse per language →
//   one linker per language (a language's linker only ever sees its
//   own files) → one discover per language (entries concatenate) →
//   ONE extract_thread.py --batch-seeds over the merged map → system
//   tier. Snapshots are regenerated by THIS script against current
//   frontend output, never hand-edited (vibegraph-fixtures contract).
//
// Run:  node --experimental-strip-types --no-warnings scripts/regen_polyglot.mjs
// Test: npm run test:polyglot (imports buildPolyglotEnvelope from here).

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { basename, dirname, join, relative, sep } from "node:path";
import {
  LANGUAGES, languageById, languageForPath, languageForFile, shouldSkipDir, COMPILED_OUTPUT_DIRS,
  batchParseCommand, linkCommand, discoverCommand, discoverProjectCommand, moduleIdentity,
} from "../src/server/languages.ts";
import { readManualSeeds } from "../src/server/manual_seeds.ts";

const __filename = fileURLToPath(import.meta.url);
export const ROOT = dirname(dirname(__filename));
const DEFAULT_SCRIPTS = join(ROOT, "scripts");
const PYENV = { ...process.env, PYTHONPATH: join(ROOT, ".pydeps") };

export const POLYGLOT_DIR = join(ROOT, "test", "fixtures", "polyglot", "shop_demo");
export const POLYGLOT_PROJECT = join(POLYGLOT_DIR, "shop_demo.project.json");

/**
 * Every source file under `root`, with the language each one resolved to.
 *
 * M-CMD.1 changed two things. The language is resolved ONCE here, with the
 * full path, so an extensionless `#!` executable can be identified (a later
 * `languageForPath` on its name alone would return null). And compiled-output
 * directories are recorded as they are skipped, because skipping in silence
 * is how a project's real source disappears without anyone noticing.
 *
 * @returns {{ files: Array<{rel: string, langId: string}>, skipped: Record<string, number> }}
 */
function walk(dir, root, skipped = {}) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = relative(root, full).split(sep).join("/");
    if (entry.isDirectory()) {
      if (!shouldSkipDir(entry.name)) { out.push(...walk(full, root, skipped).files); continue; }
      if (COMPILED_OUTPUT_DIRS.includes(entry.name)) skipped[rel] = countFiles(full);
      continue;
    }
    if (!entry.isFile()) continue;
    const lang = languageForFile(entry.name, full);
    if (lang) out.push({ rel, langId: lang.id });
  }
  out.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return { files: out, skipped };
}

/**
 * M-CMD.1 — `.vibegraph/manual_seeds.json`, for EVERY language.
 *
 * The file existed and only server.ts read it, and only for Python, so the
 * CLI ignored a human's named entry points entirely. That is the cheapest
 * possible coverage: when the detector cannot find something — a shell
 * script that is the only command a caller may run, an MCP server whose
 * tools register at runtime — a person names it and the pipeline believes
 * them. No heuristic can compete with that, and none should try.
 *
 * Unlike the Python path, a seed that does not resolve is REPORTED rather
 * than silently dropped: a human typed it, so its absence is a finding.
 *
 * Shape (both accepted): `{"seeds": [{file, irNodeId}]}` or a bare array.
 */

/** How much a skipped directory held, so the report can be specific. */
function countFiles(dir) {
  let n = 0;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) n += countFiles(join(dir, e.name));
    else if (e.isFile()) n += 1;
  }
  return n;
}

function run(cmd, { input, cwd, pipeline }) {
  // M-CRYSTAL.1 — a packaged CLI has no VibeGraph checkout: the scripts
  // directory, the python binary and its environment come from the caller.
  const bin = cmd.needsPythonEnv && pipeline.pythonBin ? pipeline.pythonBin : cmd.bin;
  const r = spawnSync(bin, cmd.argv, {
    input, cwd, encoding: "utf-8", maxBuffer: 64 * 1024 * 1024,
    env: cmd.needsPythonEnv ? pipeline.pythonEnv : process.env,
  });
  if (r.status !== 0) throw new Error(`${cmd.argv[0]} failed: ${r.stderr}`);
  return JSON.parse(r.stdout);
}

/** Group a {relPath: IR} map by registered language (the server's filesByLanguage).
 *  Keys off the IR's OWN `language` stamp rather than re-deriving from the
 *  path: the parse step already decided, and an extensionless `#!` file has
 *  no extension to re-derive from (M-CMD.1). Falls back to the path for a
 *  pre-stamped IR handed in from a committed envelope. */
function byLanguage(files) {
  const map = new Map();
  for (const [f, ir] of Object.entries(files)) {
    const lang = languageById(ir?.language) ?? languageForPath(f);
    if (!lang) continue;
    if (!map.has(lang)) map.set(lang, {});
    map.get(lang)[f] = ir;
  }
  return map;
}

/**
 * @param root the analysed project
 * @param opts M-CRYSTAL.1 — where the pipeline lives, for a caller that is
 *   not this checkout: `scriptsDir` (default this repo's scripts/),
 *   `pythonBin` (default the registry's `python3`), `pythonEnv` (default
 *   this repo's .pydeps on PYTHONPATH), `cwd` for the steps that read no
 *   files relative to it (default this repo's root; the parse step always
 *   runs in the analysed root because parse_cst.py opens paths from there).
 *   Defaults reproduce the fixture regen byte for byte (test:polyglot).
 */
export function buildPolyglotEnvelope(root = POLYGLOT_DIR, opts = {}) {
  const SCRIPTS = opts.scriptsDir ?? DEFAULT_SCRIPTS;
  const pipeline = { pythonBin: opts.pythonBin ?? null, pythonEnv: opts.pythonEnv ?? PYENV };
  const stepCwd = opts.cwd ?? ROOT;
  const { files: walked, skipped: skippedDirs } = walk(root, root);
  const perLang = new Map();
  for (const { rel: f, langId } of walked) {
    const lang = languageById(langId);
    if (!lang) continue;
    if (!perLang.has(lang)) perLang.set(lang, []);
    perLang.get(lang).push(f);
  }

  // 1. parse — one batch per language, relative paths keyed exactly as
  //    the server's relativeProjectFiles() view; language stamped per file.
  let files = {};
  const parseErrors = {};
  for (const [lang, list] of perLang) {
    const cmd = batchParseCommand(lang, SCRIPTS);
    const input = list.map((f) => `${f}\t${moduleIdentity(lang, f)}`).join("\n") + "\n";
    const parsed = run(cmd, { input, cwd: root, pipeline });
    Object.assign(parseErrors, parsed.errors ?? {});
    for (const [f, ir] of Object.entries(parsed.files ?? {})) files[f] = { language: lang.id, ...ir };
  }

  // 2. link — per language, own files only.
  const linked = {};
  for (const [lang, subset] of byLanguage(files)) {
    const cmd = linkCommand(lang, SCRIPTS);
    if (!cmd) { Object.assign(linked, subset); continue; }
    const out = run(cmd, { input: JSON.stringify({ files: subset }), cwd: stepCwd, pipeline });
    Object.assign(linked, out.files ?? subset);
  }
  files = linked;

  // 3. discover — per language; entries concatenate.
  const entryPoints = [];
  for (const [lang, subset] of byLanguage(files)) {
    const cmd = discoverCommand(lang, SCRIPTS);
    if (!cmd) continue;
    const out = run(cmd, { input: JSON.stringify({ files: subset }), cwd: stepCwd, pipeline });
    entryPoints.push(...(out.entryPoints ?? []));
  }
  // 3a. PROJECT-LEVEL discovery (M-FLOW.2): a script another file names by a
  //     literal is run, whatever its own file says. After the per-language
  //     step so a richer discovered row is never displaced.
  {
    const out = run(discoverProjectCommand(SCRIPTS), { input: JSON.stringify({ files, entryPoints }), cwd: stepCwd, pipeline });
    for (const e of out.entryPoints ?? []) if (!entryPoints.some((x) => x.id === e.id)) entryPoints.push(e);
  }

  // 3b. MANUAL SEEDS — a person's named entry points, in any language, after
  //     discovery so a seed never displaces a richer discovered row.
  const { seeds: manualSeeds, unresolvedSeeds } = (() => {
    const r = readManualSeeds(root, files);
    return { seeds: r.seeds, unresolvedSeeds: r.unresolved };
  })();
  for (const seed of manualSeeds) {
    if (!entryPoints.some((e) => e.id === seed.id)) entryPoints.push(seed);
  }

  // 4. extract — ONE batch over the merged map (threads never cross languages).
  const seeds = entryPoints.map((e) => ({ seedFile: e.file, seedId: e.irNodeId, entryPointId: e.id }));
  const extracted = run(
    { bin: "python3", argv: [join(SCRIPTS, "extract_thread.py"), "--batch-seeds"], needsPythonEnv: true },
    { input: JSON.stringify({ files, seeds }), cwd: stepCwd, pipeline },
  );
  const threads = extracted.threads ?? [];

  // 5. system tier.
  const sys = run(
    { bin: "python3", argv: [join(SCRIPTS, "build_system_tier.py")], needsPythonEnv: true },
    { input: JSON.stringify({ files, entryPoints, threads, projectRoot: root }), cwd: stepCwd, pipeline },
  );

  const symbolIndex = [];
  for (const ir of Object.values(files)) if (ir.symbolIndex) symbolIndex.push(...ir.symbolIndex);
  return {
    envelope: { version: "2.1", files, symbolIndex, entryPoints, threads, system: sys.system ?? { subsystems: [], edges: [] } },
    parseErrors,
    /** Compiled-output directories NOT walked, with what each held (M-CMD.1). */
    skippedDirs,
    /** Manual seeds a person named that did NOT resolve, with why (M-CMD.1). */
    unresolvedSeeds,
    languages: [...perLang.keys()].map((l) => l.id),
  };
}

// The main guard names THIS file rather than comparing import.meta.url to
// argv[1]: inside the M-CRYSTAL bundle import.meta.url is the bundle, which
// IS argv[1], so the old comparison ran this block (and every other bundled
// script's) at import time. Found by the first `--version` of the built CLI.
if (process.argv[1] && basename(process.argv[1]) === "regen_polyglot.mjs") {
  const { envelope, parseErrors } = buildPolyglotEnvelope();
  if (Object.keys(parseErrors).length) {
    console.error("regen_polyglot: parse errors:", JSON.stringify(parseErrors));
    process.exit(1);
  }
  writeFileSync(POLYGLOT_PROJECT, JSON.stringify(envelope, null, 2) + "\n");
  process.stderr.write(`regenerated ${relative(ROOT, POLYGLOT_PROJECT)} — ${LANGUAGES.length} languages registered, `
    + `${Object.keys(envelope.files).length} files, ${envelope.entryPoints.length} entry points, ${envelope.threads.length} threads\n`);
}
