#!/usr/bin/env node
// M-CONTRACT.1 — regenerate the POLYGLOT fixture's committed envelope:
//   test/fixtures/polyglot/shop_demo/shop_demo.project.json
//
// Mirrors server.ts's directory pipeline EXACTLY, per language, off the
// SAME registry the server dispatches through (src/server/languages.ts):
//   walk (registered extensions only) → one batch parse per language →
//   one linker per language (a language's linker only ever sees its
//   own files) → one discover per language (entries concatenate) →
//   ONE extract_thread.py --batch-seeds over the merged map → system
//   tier. Snapshots are regenerated by THIS script against current
//   frontend output, never hand-edited (vibegraph-fixtures contract).
//
// Run:  node --experimental-strip-types --no-warnings scripts/regen_polyglot.mjs
// Test: npm run test:polyglot (imports buildPolyglotEnvelope from here).

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { basename, dirname, join, relative, sep } from "node:path";
import {
  LANGUAGES, languageById, languageForPath, languageForFile, shouldSkipDir, COMPILED_OUTPUT_DIRS,
  batchParseCommand, linkCommand, discoverCommand, discoverProjectCommand, moduleIdentity,
} from "../src/server/languages.ts";
import { readManualSeeds } from "../src/server/manual_seeds.ts";
import { linkFiles as linkBash } from "./frontends/bash/link_bash.mjs";
import { linkFiles as linkJsts } from "./frontends/jsts/link_jsts.mjs";
import { linkFiles as linkCpp } from "./frontends/cpp/link_cpp.mjs";
import { linkFiles as linkRust } from "./frontends/rust/link_rust.mjs";
import { discover as discoverBash } from "./frontends/bash/discover_bash.mjs";
import { discover as discoverJsts } from "./frontends/jsts/discover_jsts.mjs";
import { discover as discoverCpp } from "./frontends/cpp/discover_cpp.mjs";
import { discover as discoverRust } from "./frontends/rust/discover_rust.mjs";
import { discoverProject } from "./discover_project.mjs";
import { readPackageManifests } from "./package_entries.mjs";

/** The Node frontends' link and discover steps, called directly. */
const IN_PROCESS = {
  bash: { link: linkBash, discover: discoverBash },
  jsts: { link: linkJsts, discover: discoverJsts },
  cpp: { link: linkCpp, discover: discoverCpp },
  rust: { link: linkRust, discover: discoverRust },
};

/** A private copy for a linker, which stamps edges and effect kinds IN
 *  PLACE: the parsed objects are shared with the parse cache, and a spawned
 *  linker only ever saw a copy that crossed a pipe. Nodes and edges are
 *  copied one level down, which is as deep as any linker writes. */
function detached(subset) {
  const out = {};
  for (const [f, ir] of Object.entries(subset)) {
    out[f] = { ...ir, nodes: (ir.nodes ?? []).map((n) => ({ ...n })), edges: (ir.edges ?? []).map((e) => ({ ...e })) };
  }
  return out;
}

const __filename = fileURLToPath(import.meta.url);
export const ROOT = dirname(dirname(__filename));
const DEFAULT_SCRIPTS = join(ROOT, "scripts");
const PYENV = { ...process.env, PYTHONPATH: join(ROOT, ".pydeps") };

export const POLYGLOT_DIR = join(ROOT, "test", "fixtures", "polyglot", "shop_demo");
export const POLYGLOT_PROJECT = join(POLYGLOT_DIR, "shop_demo.project.json");

/**
 * Every source file under `root`, with the language each one resolved to.
 *
 * M-CMD.1 changed two things. The language is resolved ONCE here, with the
 * full path, so an extensionless `#!` executable can be identified (a later
 * `languageForPath` on its name alone would return null). And compiled-output
 * directories are recorded as they are skipped, because skipping in silence
 * is how a project's real source disappears without anyone noticing.
 *
 * @returns {{ files: Array<{rel: string, langId: string}>, skipped: Record<string, number> }}
 */
function walk(dir, root, skipped = {}) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = relative(root, full).split(sep).join("/");
    if (entry.isDirectory()) {
      if (!shouldSkipDir(entry.name)) { out.push(...walk(full, root, skipped).files); continue; }
      if (COMPILED_OUTPUT_DIRS.includes(entry.name)) skipped[rel] = countFiles(full);
      continue;
    }
    if (!entry.isFile()) continue;
    const lang = languageForFile(entry.name, full);
    if (lang) out.push({ rel, langId: lang.id });
  }
  out.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return { files: out, skipped };
}

/**
 * M-CMD.1 — `.vibegraph/manual_seeds.json`, for EVERY language.
 *
 * The file existed and only server.ts read it, and only for Python, so the
 * CLI ignored a human's named entry points entirely. That is the cheapest
 * possible coverage: when the detector cannot find something — a shell
 * script that is the only command a caller may run, an MCP server whose
 * tools register at runtime — a person names it and the pipeline believes
 * them. No heuristic can compete with that, and none should try.
 *
 * Unlike the Python path, a seed that does not resolve is REPORTED rather
 * than silently dropped: a human typed it, so its absence is a finding.
 *
 * Shape (both accepted): `{"seeds": [{file, irNodeId}]}` or a bare array.
 */

/** How much a skipped directory held, so the report can be specific. */
function countFiles(dir) {
  let n = 0;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) n += countFiles(join(dir, e.name));
    else if (e.isFile()) n += 1;
  }
  return n;
}

function run(cmd, { input, cwd, pipeline }) {
  // M-CRYSTAL.1 — a packaged CLI has no VibeGraph checkout: the scripts
  // directory, the python binary and its environment come from the caller.
  const bin = cmd.needsPythonEnv && pipeline.pythonBin ? pipeline.pythonBin : cmd.bin;
  const r = spawnSync(bin, cmd.argv, {
    input, cwd, encoding: "utf-8", maxBuffer: 64 * 1024 * 1024,
    env: cmd.needsPythonEnv ? pipeline.pythonEnv : process.env,
  });
  if (r.status !== 0) throw new Error(`${cmd.argv[0]} failed: ${r.stderr}`);
  return JSON.parse(r.stdout);
}

/** Group a {relPath: IR} map by registered language (the server's filesByLanguage).
 *  Keys off the IR's OWN `language` stamp rather than re-deriving from the
 *  path: the parse step already decided, and an extensionless `#!` file has
 *  no extension to re-derive from (M-CMD.1). Falls back to the path for a
 *  pre-stamped IR handed in from a committed envelope. */
function byLanguage(files) {
  const map = new Map();
  for (const [f, ir] of Object.entries(files)) {
    const lang = languageById(ir?.language) ?? languageForPath(f);
    if (!lang) continue;
    if (!map.has(lang)) map.set(lang, {});
    map.get(lang)[f] = ir;
  }
  return map;
}

/**
 * @param root the analysed project
 * @param opts M-CRYSTAL.1 — where the pipeline lives, for a caller that is
 *   not this checkout: `scriptsDir` (default this repo's scripts/),
 *   `pythonBin` (default the registry's `python3`), `pythonEnv` (default
 *   this repo's .pydeps on PYTHONPATH), `cwd` for the steps that read no
 *   files relative to it (default this repo's root; the parse step always
 *   runs in the analysed root because parse_cst.py opens paths from there).
 *   Defaults reproduce the fixture regen byte for byte (test:polyglot).
 */
export function buildPolyglotEnvelope(root = POLYGLOT_DIR, opts = {}) {
  const SCRIPTS = opts.scriptsDir ?? DEFAULT_SCRIPTS;
  const pipeline = { pythonBin: opts.pythonBin ?? null, pythonEnv: opts.pythonEnv ?? PYENV };
  const stepCwd = opts.cwd ?? ROOT;
  // Optional stage timings (ms), for the cache measurements and --timing.
  const timings = opts.timings ?? null;
  let tMark = Date.now();
  const lap = (name) => { if (timings) { const now = Date.now(); timings[name] = now - tMark; tMark = now; } };
  const { files: walked, skipped: skippedDirs } = walk(root, root);
  const perLang = new Map();
  for (const { rel: f, langId } of walked) {
    const lang = languageById(langId);
    if (!lang) continue;
    if (!perLang.has(lang)) perLang.set(lang, []);
    perLang.get(lang).push(f);
  }

  // 1. parse — one batch per language, relative paths keyed exactly as
  //    the server's relativeProjectFiles() view; language stamped per file.
  let files = {};
  const parseErrors = {};
  // `opts.parseCache` (scripts/envelope_cache.mjs) answers a file whose
  // bytes and parse context have not moved; only the rest are parsed.
  for (const [lang, all] of perLang) {
    const list = [];
    for (const f of all) {
      const hit = opts.parseCache?.lookup(f, lang.id) ?? null;
      if (hit) files[f] = hit; else list.push(f);
    }
    if (!list.length) continue;
    const cmd = batchParseCommand(lang, SCRIPTS);
    const input = list.map((f) => `${f}\t${moduleIdentity(lang, f)}`).join("\n") + "\n";
    const parsed = run(cmd, { input, cwd: root, pipeline });
    // A file the frontend read PARTLY carries an IR (and `degraded` on it) and
    // an errors entry beside it. It is not a parse failure: every consumer of
    // parseErrors says "those files carry no IR", and the hooks refused edits
    // to it (found 2026-09-29 on a private production codebase). Failed = no IR; partial is read
    // from `ir.degraded` below, which also survives the parse cache.
    for (const [f, msg] of Object.entries(parsed.errors ?? {})) {
      if (!parsed.files?.[f]) parseErrors[f] = msg;
    }
    for (const [f, ir] of Object.entries(parsed.files ?? {})) {
      files[f] = { language: lang.id, ...ir };
      opts.parseCache?.store(f, lang.id, files[f]);
    }
  }
  // Walked order, so a partly cached parse keys the map exactly as a full one.
  files = Object.fromEntries(walked.filter(({ rel }) => rel in files).map(({ rel }) => [rel, files[rel]]));

  lap("parse");
  // 2. link — per language, own files only. The Node linkers and
  //    discoverers run IN-PROCESS (2026-09-29): measured on a private production codebase, their
  //    spawns spent ~3.4 s of the ~3.9 s serialising the map through a pipe
  //    (40 MB each way to the TypeScript linker, 85 MB to project discovery),
  //    while the work itself took ~0.3 s. Same functions, same output — the
  //    CLI path still exists (VG_SPAWN_PIPELINE=1 restores it). Python stays
  //    a spawn: it is a different runtime.
  const inProcess = process.env.VG_SPAWN_PIPELINE !== "1" && opts.inProcess !== false;
  const linked = {};
  for (const [lang, subset] of byLanguage(files)) {
    const local = inProcess ? IN_PROCESS[lang.id] : null;
    if (local) { Object.assign(linked, local.link(detached(subset))); continue; }
    const cmd = linkCommand(lang, SCRIPTS);
    if (!cmd) { Object.assign(linked, subset); continue; }
    const out = run(cmd, { input: JSON.stringify({ files: subset }), cwd: stepCwd, pipeline });
    Object.assign(linked, out.files ?? subset);
  }
  files = linked;

  lap("link");
  // 3. discover — per language; entries concatenate.
  const entryPoints = [];
  for (const [lang, subset] of byLanguage(files)) {
    const local = inProcess ? IN_PROCESS[lang.id] : null;
    if (local) { entryPoints.push(...local.discover(subset)); continue; }
    const cmd = discoverCommand(lang, SCRIPTS);
    if (!cmd) continue;
    const out = run(cmd, { input: JSON.stringify({ files: subset }), cwd: stepCwd, pipeline });
    entryPoints.push(...(out.entryPoints ?? []));
  }
  // 3a. PROJECT-LEVEL discovery (M-FLOW.2): a script another file names by a
  //     literal is run, whatever its own file says. After the per-language
  //     step so a richer discovered row is never displaced.
  {
    // 2026-10-01 — and what each package.json runs (bin, scripts).
    const manifests = readPackageManifests(root);
    const found = inProcess
      ? discoverProject(files, entryPoints, manifests)
      : run(discoverProjectCommand(SCRIPTS), { input: JSON.stringify({ files, entryPoints, manifests }), cwd: stepCwd, pipeline }).entryPoints ?? [];
    for (const e of found) if (!entryPoints.some((x) => x.id === e.id)) entryPoints.push(e);
  }

  // 3b. MANUAL SEEDS — a person's named entry points, in any language, after
  //     discovery so a seed never displaces a richer discovered row.
  const { seeds: manualSeeds, unresolvedSeeds } = (() => {
    const r = readManualSeeds(root, files);
    return { seeds: r.seeds, unresolvedSeeds: r.unresolved };
  })();
  for (const seed of manualSeeds) {
    if (!entryPoints.some((e) => e.id === seed.id)) entryPoints.push(seed);
  }

  lap("discover");
  // 4. extract — ONE batch over the merged map (threads never cross languages).
  const seeds = entryPoints.map((e) => ({ seedFile: e.file, seedId: e.irNodeId, entryPointId: e.id }));
  // `opts.threadCache` may hand back threads whose inputs did not move; the
  // rest are extracted, and the list is reassembled in seed order so the
  // result is the one a full extraction would give.
  const reuse = opts.threadCache?.select(seeds, files) ?? null;
  const toExtract = reuse ? reuse.toExtract : seeds;
  const fresh = toExtract.length
    ? run(
      { bin: "python3", argv: [join(SCRIPTS, "extract_thread.py"), "--batch-seeds"], needsPythonEnv: true },
      { input: JSON.stringify({ files, seeds: toExtract }), cwd: stepCwd, pipeline },
    ).threads ?? []
    : [];
  let threads = fresh;
  if (reuse) {
    const key = (ep, file) => `${ep}\u0000${file}`;
    const byKey = new Map(fresh.map((t) => [key(t.entryPointId, t.seed?.file), t]));
    threads = [];
    for (const s of seeds) {
      const t = reuse.cached.get(key(s.entryPointId, s.seedFile)) ?? byKey.get(key(s.entryPointId, s.seedFile));
      if (t) threads.push(t);
    }
  }

  lap("extract");
  // 5. system tier — skipped when the caller only checks (opts.skipSystem).
  const sys = opts.skipSystem ? { system: null } : run(
    { bin: "python3", argv: [join(SCRIPTS, "build_system_tier.py")], needsPythonEnv: true },
    { input: JSON.stringify({ files, entryPoints, threads, projectRoot: root }), cwd: stepCwd, pipeline },
  );

  lap("system");
  const symbolIndex = [];
  for (const ir of Object.values(files)) if (ir.symbolIndex) symbolIndex.push(...ir.symbolIndex);
  return {
    envelope: {
      version: "2.1", files, symbolIndex, entryPoints, threads,
      ...(opts.skipSystem ? {} : { system: sys.system ?? { subsystems: [], edges: [] } }),
    },
    parseErrors,
    /** Files read PARTLY (they carry an IR with `degraded`), by message. */
    partialParses: Object.fromEntries(Object.entries(files).filter(([, ir]) => ir.degraded).map(([f, ir]) => [f, typeof ir.degraded === "string" ? ir.degraded : JSON.stringify(ir.degraded)])),
    /** Compiled-output directories NOT walked, with what each held (M-CMD.1). */
    skippedDirs,
    /** Manual seeds a person named that did NOT resolve, with why (M-CMD.1). */
    unresolvedSeeds,
    languages: [...perLang.keys()].map((l) => l.id),
  };
}

// The main guard names THIS file rather than comparing import.meta.url to
// argv[1]: inside the M-CRYSTAL bundle import.meta.url is the bundle, which
// IS argv[1], so the old comparison ran this block (and every other bundled
// script's) at import time. Found by the first `--version` of the built CLI.
if (process.argv[1] && basename(process.argv[1]) === "regen_polyglot.mjs") {
  const { envelope, parseErrors } = buildPolyglotEnvelope();
  if (Object.keys(parseErrors).length) {
    console.error("regen_polyglot: parse errors:", JSON.stringify(parseErrors));
    process.exit(1);
  }
  writeFileSync(POLYGLOT_PROJECT, JSON.stringify(envelope, null, 2) + "\n");
  process.stderr.write(`regenerated ${relative(ROOT, POLYGLOT_PROJECT)} — ${LANGUAGES.length} languages registered, `
    + `${Object.keys(envelope.files).length} files, ${envelope.entryPoints.length} entry points, ${envelope.threads.length} threads\n`);
}
