#!/usr/bin/env python3
"""
Vendor a thread-view demo fixture from an upstream open-source library
(M4b wave 5).

Per PLAN.md S1.3, big_demo is a "visual demo fixture" -- not
snapshot-tested, just rendered for screenshots/video on at least two
seed functions. We vendor the upstream source verbatim (no
anonymisation) and commit it alongside a SOURCE.md recording the
upstream repo, commit hash, and license. Re-running this script with
the same --pin produces byte-identical output.

Default target: Flask-Login 0.6.3 (MIT). 8 .py files / ~43KB total.

Usage:
    python3 scripts/synth_thread_fixture.py            # default Flask-Login
    python3 scripts/synth_thread_fixture.py --check    # verify pinned files
                                                       # match committed
                                                       # fixture byte-for-byte

The script is the source of truth for *how* the fixture was generated.
Once the fixture is committed, the script's main job is the --check
flag for future "is the vendor still consistent" CI sanity.
"""

import argparse
import hashlib
import json
import os
import sys
import urllib.request
import urllib.error
from typing import Dict, List, Tuple

# ─────────────────────────────────────────── pinned upstream ────────

DEFAULT_REPO = "maxcountryman/flask-login"
DEFAULT_PIN = "88eca62d4f87a36b1339ea8fe5a8b7ad878cf3ef"  # tag 0.6.3
DEFAULT_SUBDIR = "src/flask_login"
DEFAULT_LICENSE_PATH = "LICENSE"
DEFAULT_TARGET = "test/fixtures/threads/big_demo"


def fetch_json(url: str) -> dict:
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def fetch_raw(repo: str, pin: str, path: str) -> bytes:
    url = f"https://raw.githubusercontent.com/{repo}/{pin}/{path}"
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read()


def list_python_files(repo: str, pin: str, subdir: str) -> List[Tuple[str, int]]:
    """Return [(name, size), ...] for .py files in subdir at pin."""
    api = f"https://api.github.com/repos/{repo}/contents/{subdir}?ref={pin}"
    entries = fetch_json(api)
    return [(e["name"], e.get("size", 0)) for e in entries
            if e["type"] == "file" and e["name"].endswith(".py")]


def write_source_md(target: str, repo: str, pin: str, subdir: str,
                    files: List[Tuple[str, int, str]], license_text: str) -> None:
    """files: [(name, size, sha256), ...]."""
    total_lines = 0
    for fn, _, _ in files:
        with open(os.path.join(target, fn), "rb") as f:
            total_lines += sum(1 for _ in f)
    body = [
        "# Upstream provenance",
        "",
        "This directory is a verbatim vendor of:",
        "",
        f"- **Repo:** [{repo}](https://github.com/{repo})",
        f"- **Pin:** `{pin}` (resolves to tag `0.6.3` at fetch time)",
        f"- **Subdir:** `{subdir}/`",
        f"- **License:** MIT (see `LICENSE.upstream` in this dir)",
        "",
        f"Generated by `scripts/synth_thread_fixture.py`. Files included "
        f"(SHA-256 fingerprints for reproducibility):",
        "",
    ]
    for fn, sz, sha in files:
        body.append(f"- `{fn}` -- {sz} bytes -- `sha256:{sha[:16]}...`")
    body += [
        "",
        f"**Total:** {len(files)} .py files, {total_lines} lines.",
        "",
        "Re-vendor: `python3 scripts/synth_thread_fixture.py`. Verify "
        "against the committed copy: `python3 scripts/synth_thread_fixture.py "
        "--check`. The script is hard-coded to the pin above; bumping the "
        "pin is an intentional fixture refresh.",
        "",
        "## Why this fixture exists",
        "",
        "PLAN.md S1.3 calls for a 10-15 file / ~1000 LOC visual-demo "
        "fixture that renders a recognisable thread on at least two "
        "seeds. Flask-Login's `login_user` and `logout_user` give us two "
        "well-known control flows that touch the session, the user "
        "loader, and the unauthorized handler -- thread output looks "
        "like the routing of a real auth library, not a synthetic toy.",
        "",
        "## Out of scope",
        "",
        "No anonymisation, no edits. This is a render target, not a "
        "snapshot test (see `aero_demo` for the snapshot fixture). If "
        "Flask-Login's upstream changes shape in a way that breaks our "
        "renderer assumptions, we change the pin, not the source.",
    ]
    with open(os.path.join(target, "SOURCE.md"), "w") as f:
        f.write("\n".join(body) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="Vendor a thread-view demo fixture.")
    ap.add_argument("--repo", default=DEFAULT_REPO,
                    help="owner/name on GitHub")
    ap.add_argument("--pin", default=DEFAULT_PIN,
                    help="commit SHA (NOT a tag) for reproducibility")
    ap.add_argument("--subdir", default=DEFAULT_SUBDIR,
                    help="path inside the repo to vendor")
    ap.add_argument("--target", default=DEFAULT_TARGET,
                    help="directory to write into (relative to project root)")
    ap.add_argument("--check", action="store_true",
                    help="verify the existing target matches the upstream pin")
    args = ap.parse_args()

    target = os.path.abspath(args.target)
    os.makedirs(target, exist_ok=True)

    print(f"Listing {args.repo}@{args.pin}:{args.subdir}/ ...")
    entries = list_python_files(args.repo, args.pin, args.subdir)
    if not entries:
        print("No .py files found at upstream subdir.", file=sys.stderr)
        return 2

    summary: List[Tuple[str, int, str]] = []
    mismatches: List[str] = []
    for name, size in entries:
        path = f"{args.subdir}/{name}"
        body = fetch_raw(args.repo, args.pin, path)
        sha = hashlib.sha256(body).hexdigest()
        summary.append((name, len(body), sha))
        out_path = os.path.join(target, name)
        if args.check:
            if not os.path.exists(out_path):
                mismatches.append(f"{name}: missing locally")
                continue
            with open(out_path, "rb") as f:
                local = f.read()
            if local != body:
                mismatches.append(f"{name}: {len(local)} bytes locally, "
                                  f"{len(body)} bytes upstream")
        else:
            with open(out_path, "wb") as f:
                f.write(body)
            print(f"  wrote {name} -- {len(body)} bytes")

    if args.check:
        if mismatches:
            print("FAIL: vendor drift:", file=sys.stderr)
            for m in mismatches:
                print(f"  {m}", file=sys.stderr)
            return 1
        print(f"OK: {len(summary)} files match upstream pin.")
        return 0

    # Fetch LICENSE alongside so attribution sits next to the source.
    try:
        license_body = fetch_raw(args.repo, args.pin, DEFAULT_LICENSE_PATH)
    except urllib.error.HTTPError:
        license_body = b"(LICENSE file not present at upstream root.)\n"
    with open(os.path.join(target, "LICENSE.upstream"), "wb") as f:
        f.write(license_body)
    write_source_md(target, args.repo, args.pin, args.subdir, summary,
                    license_body.decode("utf-8", errors="replace"))
    print(f"Done. {len(summary)} .py files vendored to {target}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
